export enum Resource {
  coal,
  oil,
  garbage,
  uranium,

  hybrid,
  renewable,
}

export type PowerPlant = {
  cost: number;
  resources: { [r in Resource]?: number };
  power: number;
  index: number;
  isPlug: boolean;
};

export const deck: PowerPlant[] = [
  { cost: 3, resources: { [Resource.oil]: 2 }, power: 1 },
  { cost: 4, resources: { [Resource.coal]: 2 }, power: 1 },
  { cost: 5, resources: { [Resource.hybrid]: 2 }, power: 1 },
  { cost: 6, resources: { [Resource.garbage]: 1 }, power: 1 },
  { cost: 7, resources: { [Resource.oil]: 3 }, power: 2 },
  { cost: 8, resources: { [Resource.coal]: 3 }, power: 2 },
  { cost: 9, resources: { [Resource.oil]: 1 }, power: 1 },
  { cost: 10, resources: { [Resource.coal]: 2 }, power: 2 },
  { cost: 11, resources: { [Resource.uranium]: 1 }, power: 2 },
  { cost: 12, resources: { [Resource.hybrid]: 2 }, power: 2 },
  { cost: 13, resources: { [Resource.renewable]: 0 }, power: 1 },
  { cost: 14, resources: { [Resource.garbage]: 2 }, power: 2 },
  { cost: 15, resources: { [Resource.coal]: 2 }, power: 3 },
  { cost: 16, resources: { [Resource.oil]: 2 }, power: 3 },
  { cost: 17, resources: { [Resource.uranium]: 1 }, power: 2 },
  { cost: 18, resources: { [Resource.renewable]: 0 }, power: 2 },
  { cost: 19, resources: { [Resource.garbage]: 2 }, power: 3 },
  { cost: 20, resources: { [Resource.coal]: 3 }, power: 5 },
  { cost: 21, resources: { [Resource.hybrid]: 2 }, power: 4 },
  { cost: 22, resources: { [Resource.renewable]: 0 }, power: 2 },
  { cost: 23, resources: { [Resource.uranium]: 1 }, power: 3 },
  { cost: 24, resources: { [Resource.garbage]: 2 }, power: 4 },
  { cost: 25, resources: { [Resource.coal]: 2 }, power: 5 },
  { cost: 26, resources: { [Resource.oil]: 2 }, power: 5 },
  { cost: 27, resources: { [Resource.renewable]: 0 }, power: 3 },
  { cost: 28, resources: { [Resource.uranium]: 1 }, power: 4 },
  { cost: 29, resources: { [Resource.hybrid]: 1 }, power: 4 },
  { cost: 30, resources: { [Resource.garbage]: 3 }, power: 6 },
  { cost: 31, resources: { [Resource.coal]: 3 }, power: 6 },
  { cost: 32, resources: { [Resource.oil]: 3 }, power: 6 },
  { cost: 33, resources: { [Resource.renewable]: 0 }, power: 4 },
  { cost: 34, resources: { [Resource.uranium]: 1 }, power: 5 },
  { cost: 35, resources: { [Resource.oil]: 1 }, power: 5 },
  { cost: 36, resources: { [Resource.coal]: 3 }, power: 7 },
  { cost: 37, resources: { [Resource.renewable]: 0 }, power: 4 },
  { cost: 38, resources: { [Resource.garbage]: 3 }, power: 7 },
  { cost: 39, resources: { [Resource.uranium]: 1 }, power: 6 },
  { cost: 40, resources: { [Resource.oil]: 2 }, power: 6 },
  { cost: 42, resources: { [Resource.coal]: 2 }, power: 6 },
  { cost: 44, resources: { [Resource.renewable]: 0 }, power: 5 },
  { cost: 46, resources: { [Resource.hybrid]: 3 }, power: 7 },
  { cost: 50, resources: { [Resource.renewable]: 0 }, power: 6 },
].map((pp, index) => ({
  ...pp,
  index,
  isPlug: pp.cost <= 15,
}));

export type Map = {
  name: string;
  img: string;
  cities: { name: string; x: number; y: number }[];
  edges: { c1: string; c2: string; cost: number }[];
};

export const maps: Map[] = [
  {
    name: "germany",
    img: "https://cf.geekdo-images.com/S4goYZXgXYxg6YM3XjCc3Q__original/img/8MwA59fnTZn8RdC4py4cryJ2uTM=/0x0/filters:format(jpeg)/pic354241.jpg",
    cities: [
      { name: "flensburg", x: 631, y: 69 },
      { name: "kiel", x: 708, y: 195 },
      { name: "cuxhaven", x: 525, y: 307 },
      { name: "wilhelmshaven", x: 421, y: 384 },
      { name: "bremen", x: 549, y: 505 },
      { name: "hamburg", x: 698, y: 384 },
      { name: "hannover", x: 701, y: 689 },
      { name: "osnabruck", x: 433, y: 659 },
      { name: "munster", x: 347, y: 779 },
      { name: "dortmund", x: 372, y: 925 },
      { name: "essen", x: 239, y: 867 },
      { name: "duisburg", x: 143, y: 832 },
      { name: "dusseldorf", x: 169, y: 980 },
      { name: "kassel", x: 620, y: 960 },
      { name: "aachen", x: 123, y: 1121 },
      { name: "koln", x: 269, y: 1074 },
      { name: "trier", x: 186, y: 1347 },
      { name: "saarbrucken", x: 317, y: 1490 },
      { name: "mannheim", x: 516, y: 1451 },
      { name: "wiesbaden", x: 438, y: 1269 },
      { name: "frankfurt-m", x: 530, y: 1226 },
      { name: "freiburg", x: 385, y: 1762 },
      { name: "konstanz", x: 560, y: 1842 },
      { name: "stuttgart", x: 562, y: 1610 },
      { name: "augsburg", x: 810, y: 1661 },
      { name: "munchen", x: 961, y: 1761 },
      { name: "regensburg", x: 1011, y: 1540 },
      { name: "passau", x: 1239, y: 1643 },
      { name: "nurnberg", x: 892, y: 1422 },
      { name: "wurzburg", x: 721, y: 1338 },
      { name: "fulda", x: 696, y: 1146 },
      { name: "erfurt", x: 892, y: 1032 },
      { name: "halle", x: 1003, y: 901 },
      { name: "leipzig", x: 1084, y: 955 },
      { name: "dresden", x: 1301, y: 1039 },
      { name: "frankfurt-d", x: 1360, y: 695 },
      { name: "berlin", x: 1202, y: 647 },
      { name: "magdeburg", x: 977, y: 708 },
      { name: "schwerin", x: 920, y: 395 },
      { name: "rostock", x: 1011, y: 234 },
      { name: "torgelow", x: 1299, y: 382 },
      { name: "lubeck", x: 819, y: 281 },
    ],
    edges: [
      { c1: "flensburg", c2: "kiel", cost: 4 },
      { c1: "kiel", c2: "hamburg", cost: 8 },
      { c1: "hamburg", c2: "lubeck", cost: 6 },
      { c1: "lubeck", c2: "schwerin", cost: 6 },
      { c1: "schwerin", c2: "hannover", cost: 19 },
      { c1: "hannover", c2: "hamburg", cost: 17 },
      { c1: "cuxhaven", c2: "bremen", cost: 8 },
      { c1: "bremen", c2: "hamburg", cost: 11 },
      { c1: "cuxhaven", c2: "hamburg", cost: 11 },
      { c1: "rostock", c2: "torgelow", cost: 19 },
      { c1: "torgelow", c2: "schwerin", cost: 19 },
      { c1: "schwerin", c2: "rostock", cost: 6 },
      { c1: "berlin", c2: "schwerin", cost: 18 },
      { c1: "magdeburg", c2: "schwerin", cost: 16 },
      { c1: "magdeburg", c2: "berlin", cost: 10 },
      { c1: "berlin", c2: "torgelow", cost: 15 },
      { c1: "berlin", c2: "frankfurt-d", cost: 6 },
      { c1: "dresden", c2: "frankfurt-d", cost: 16 },
      { c1: "frankfurt-d", c2: "leipzig", cost: 21 },
      { c1: "halle", c2: "berlin", cost: 17 },
      { c1: "halle", c2: "leipzig", cost: 0 },
      { c1: "magdeburg", c2: "halle", cost: 11 },
      { c1: "erfurt", c2: "dresden", cost: 19 },
      { c1: "halle", c2: "erfurt", cost: 6 },
      { c1: "leipzig", c2: "dresden", cost: 13 },
      { c1: "hannover", c2: "magdeburg", cost: 15 },
      { c1: "hamburg", c2: "schwerin", cost: 6 },
      { c1: "kiel", c2: "lubeck", cost: 4 },
      { c1: "wilhelmshaven", c2: "osnabruck", cost: 14 },
      { c1: "osnabruck", c2: "bremen", cost: 11 },
      { c1: "wilhelmshaven", c2: "bremen", cost: 11 },
      { c1: "bremen", c2: "hannover", cost: 10 },
      { c1: "hannover", c2: "osnabruck", cost: 16 },
      { c1: "osnabruck", c2: "munster", cost: 7 },
      { c1: "munster", c2: "essen", cost: 6 },
      { c1: "essen", c2: "duisburg", cost: 0 },
      { c1: "essen", c2: "dusseldorf", cost: 2 },
      { c1: "essen", c2: "dortmund", cost: 4 },
      { c1: "munster", c2: "dortmund", cost: 2 },
      { c1: "osnabruck", c2: "kassel", cost: 20 },
      { c1: "kassel", c2: "hannover", cost: 15 },
      { c1: "hannover", c2: "erfurt", cost: 19 },
      { c1: "erfurt", c2: "kassel", cost: 15 },
      { c1: "fulda", c2: "erfurt", cost: 13 },
      { c1: "kassel", c2: "fulda", cost: 8 },
      { c1: "dortmund", c2: "kassel", cost: 18 },
      { c1: "kassel", c2: "frankfurt-m", cost: 13 },
      { c1: "frankfurt-m", c2: "dortmund", cost: 20 },
      { c1: "dortmund", c2: "koln", cost: 10 },
      { c1: "koln", c2: "dusseldorf", cost: 4 },
      { c1: "dusseldorf", c2: "aachen", cost: 9 },
      { c1: "aachen", c2: "koln", cost: 7 },
      { c1: "frankfurt-m", c2: "fulda", cost: 8 },
      { c1: "koln", c2: "wiesbaden", cost: 21 },
      { c1: "wiesbaden", c2: "trier", cost: 18 },
      { c1: "trier", c2: "koln", cost: 20 },
      { c1: "aachen", c2: "trier", cost: 19 },
      { c1: "saarbrucken", c2: "wiesbaden", cost: 10 },
      { c1: "wiesbaden", c2: "mannheim", cost: 11 },
      { c1: "mannheim", c2: "saarbrucken", cost: 11 },
      { c1: "saarbrucken", c2: "stuttgart", cost: 17 },
      { c1: "stuttgart", c2: "mannheim", cost: 6 },
      { c1: "mannheim", c2: "wurzburg", cost: 10 },
      { c1: "wurzburg", c2: "fulda", cost: 11 },
      { c1: "frankfurt-m", c2: "wurzburg", cost: 13 },
      { c1: "wurzburg", c2: "nurnberg", cost: 8 },
      { c1: "nurnberg", c2: "erfurt", cost: 21 },
      { c1: "trier", c2: "saarbrucken", cost: 11 },
      { c1: "konstanz", c2: "freiburg", cost: 14 },
      { c1: "freiburg", c2: "stuttgart", cost: 16 },
      { c1: "stuttgart", c2: "konstanz", cost: 16 },
      { c1: "konstanz", c2: "augsburg", cost: 17 },
      { c1: "augsburg", c2: "stuttgart", cost: 15 },
      { c1: "stuttgart", c2: "wurzburg", cost: 12 },
      { c1: "wurzburg", c2: "augsburg", cost: 19 },
      { c1: "augsburg", c2: "munchen", cost: 6 },
      { c1: "munchen", c2: "passau", cost: 14 },
      { c1: "passau", c2: "regensburg", cost: 12 },
      { c1: "regensburg", c2: "munchen", cost: 10 },
      { c1: "regensburg", c2: "augsburg", cost: 13 },
      { c1: "nurnberg", c2: "regensburg", cost: 12 },
      { c1: "nurnberg", c2: "augsburg", cost: 18 },
    ],
  },
];
