import { ActionType, PlayerColor, ReputationSlotType, ShipPartSlotType, ShipType, SpeciesId } from '../enums';
import type { SpeciesDefinition } from '../types/species';

export const SPECIES: Readonly<Record<SpeciesId, SpeciesDefinition>> = Object.freeze({
  [SpeciesId.EridaniEmpire]: {
    id: SpeciesId.EridaniEmpire,
    color: PlayerColor.Red,
    name: 'Eridani Empire',
    subtitle: 'Wealthy Imperialists',
    homeSectorId: '222',
    startingResources: {
      materials: 4,
      science: 2,
      money: 26,
    },
    startingStorage: {
      materials: 0,
      science: 0,
      money: 0,
    },
    tradeRate: 3,
    colonyShips: 3,
    influenceDiscs: 11,
    ambassadors: 3,
    startingTechs: ['gauss_shield_grid', 'fusion_drive', 'plasma_cannon'],
    activationLimits: {
      [ActionType.Explore]: 1,
      [ActionType.Research]: 1,
      [ActionType.Upgrade]: 2,
      [ActionType.Build]: 2,
      [ActionType.Move]: 2,
      [ActionType.Influence]: 2,
    },
    startingFleet: [
      { shipType: ShipType.Interceptor, count: 1 },
    ],
    blueprintOverrides: {
      [ShipType.Interceptor]: { baseEnergy: 1 },
      [ShipType.Cruiser]: { baseEnergy: 1 },
      [ShipType.Dreadnought]: { baseEnergy: 1 },
    },
    buildingCosts: {
      [ShipType.Interceptor]: 3,
      [ShipType.Cruiser]: 5,
      [ShipType.Dreadnought]: 8,
      [ShipType.Starbase]: 3,
      orbital: 4,
      monolith: 10,
    },
    specialAbilities: [
      {
        id: 'eridani_draw_rep',
        description: 'Draw 2 reputation tiles during setup and keep them.',
        effectType: 'setup_draw_reputation',
        params: { count: 2 },
      },
      {
        id: 'eridani_fewer_discs',
        description: 'Start with 2 fewer influence discs (11 instead of 13).',
        effectType: 'influence_disc_modifier',
        params: { modifier: -2 },
      },
      {
        id: 'eridani_extra_energy',
        description: 'All ship blueprints have +1 base energy.',
        effectType: 'blueprint_energy_bonus',
        params: { bonus: 1 },
      },
    ],
    reputationSlots: [ReputationSlotType.Shared, ReputationSlotType.Shared, ReputationSlotType.Shared, ReputationSlotType.Shared],
    baseInitiativeOrder: 3,
  },

  [SpeciesId.HydranProgress]: {
    id: SpeciesId.HydranProgress,
    color: PlayerColor.Blue,
    name: 'Hydran Progress',
    subtitle: 'Science Collective',
    homeSectorId: '224',
    startingResources: {
      materials: 2,
      science: 6,
      money: 2,
    },
    startingStorage: {
      materials: 0,
      science: 0,
      money: 0,
    },
    tradeRate: 3,
    colonyShips: 3,
    influenceDiscs: 13,
    ambassadors: 3,
    startingTechs: ['advanced_labs'],
    activationLimits: {
      [ActionType.Explore]: 1,
      [ActionType.Research]: 2,
      [ActionType.Upgrade]: 2,
      [ActionType.Build]: 2,
      [ActionType.Move]: 2,
      [ActionType.Influence]: 2,
    },
    startingFleet: [
      { shipType: ShipType.Interceptor, count: 1 },
    ],
    blueprintOverrides: {},
    buildingCosts: {
      [ShipType.Interceptor]: 3,
      [ShipType.Cruiser]: 5,
      [ShipType.Dreadnought]: 8,
      [ShipType.Starbase]: 3,
      orbital: 4,
      monolith: 10,
    },
    specialAbilities: [
      {
        id: 'hydran_advanced_science',
        description: 'Start with 1 population cube on an advanced science population square.',
        effectType: 'starting_advanced_pop',
        params: { resourceType: 'science', count: 1 },
      },
    ],
    reputationSlots: [ReputationSlotType.Ambassador, ReputationSlotType.Shared, ReputationSlotType.Shared, ReputationSlotType.Shared],
    baseInitiativeOrder: 4,
  },

  [SpeciesId.Planta]: {
    id: SpeciesId.Planta,
    color: PlayerColor.Green,
    name: 'Planta',
    subtitle: 'Organic Spreaders',
    homeSectorId: '226',
    startingResources: {
      materials: 4,
      science: 3,
      money: 2,
    },
    startingStorage: {
      materials: 0,
      science: 0,
      money: 0,
    },
    tradeRate: 3,
    colonyShips: 4,
    influenceDiscs: 13,
    ambassadors: 3,
    startingTechs: ['starbase_tech'],
    activationLimits: {
      [ActionType.Explore]: 2,
      [ActionType.Research]: 1,
      [ActionType.Upgrade]: 2,
      [ActionType.Build]: 2,
      [ActionType.Move]: 2,
      [ActionType.Influence]: 2,
    },
    startingFleet: [
      { shipType: ShipType.Interceptor, count: 1 },
    ],
    blueprintOverrides: {
      [ShipType.Interceptor]: {
        baseInitiative: 2,
        baseComputer: 1,
        baseEnergy: 1,
        slots: [
          { slotType: ShipPartSlotType.Any, defaultPart: 'nuclear_source' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'nuclear_drive' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'ion_cannon' },
        ],
      },
      [ShipType.Cruiser]: {
        baseInitiative: 1,
        baseComputer: 1,
        baseEnergy: 1,
        slots: [
          { slotType: ShipPartSlotType.Any, defaultPart: 'nuclear_source' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'nuclear_drive' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'ion_cannon' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'hull' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'electron_computer' },
        ],
      },
      [ShipType.Dreadnought]: {
        baseInitiative: 0,
        baseComputer: 1,
        baseEnergy: 1,
        slots: [
          { slotType: ShipPartSlotType.Any, defaultPart: 'nuclear_source' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'nuclear_drive' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'ion_cannon' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'ion_cannon' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'hull' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'hull' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'electron_computer' },
        ],
      },
      [ShipType.Starbase]: {
        baseInitiative: 3,
        baseComputer: 1,
        baseEnergy: 4,
        slots: [
          { slotType: ShipPartSlotType.Any, defaultPart: 'ion_cannon' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'electron_computer' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'hull' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'hull' },
        ],
      },
    },
    buildingCosts: {
      [ShipType.Interceptor]: 3,
      [ShipType.Cruiser]: 5,
      [ShipType.Dreadnought]: 8,
      [ShipType.Starbase]: 3,
      orbital: 4,
      monolith: 10,
    },
    specialAbilities: [
      {
        id: 'planta_auto_destroy_pop',
        description: 'Population cubes are automatically destroyed when enemy ships enter the sector.',
        effectType: 'auto_destroy_population',
        params: {},
      },
      {
        id: 'planta_sector_vp',
        description: '+1 VP per controlled sector at end of game.',
        effectType: 'scoring_per_sector',
        params: { vpPerSector: 1 },
      },
      {
        id: 'planta_reduced_initiative',
        description: 'All ship blueprints have reduced initiative bonuses.',
        effectType: 'initiative_modifier',
        params: {},
      },
    ],
    reputationSlots: [ReputationSlotType.Ambassador, ReputationSlotType.Shared, ReputationSlotType.Shared, ReputationSlotType.Shared],
    baseInitiativeOrder: 6,
  },

  [SpeciesId.DescendantsOfDraco]: {
    id: SpeciesId.DescendantsOfDraco,
    color: PlayerColor.Yellow,
    name: 'Descendants of Draco',
    subtitle: 'Ancient Allies',
    homeSectorId: '228',
    startingResources: {
      materials: 3,
      science: 4,
      money: 2,
    },
    startingStorage: {
      materials: 0,
      science: 0,
      money: 0,
    },
    tradeRate: 3,
    colonyShips: 3,
    influenceDiscs: 13,
    ambassadors: 3,
    startingTechs: ['fusion_drive'],
    activationLimits: {
      [ActionType.Explore]: 1,
      [ActionType.Research]: 1,
      [ActionType.Upgrade]: 2,
      [ActionType.Build]: 2,
      [ActionType.Move]: 2,
      [ActionType.Influence]: 2,
    },
    startingFleet: [
      { shipType: ShipType.Interceptor, count: 1 },
    ],
    blueprintOverrides: {},
    buildingCosts: {
      [ShipType.Interceptor]: 3,
      [ShipType.Cruiser]: 5,
      [ShipType.Dreadnought]: 8,
      [ShipType.Starbase]: 3,
      orbital: 4,
      monolith: 10,
    },
    specialAbilities: [
      {
        id: 'draco_double_explore',
        description: 'Draw 2 sector tiles when exploring; choose 1, discard the other.',
        effectType: 'explore_draw_extra',
        params: { drawCount: 2, keepCount: 1 },
      },
      {
        id: 'draco_ancient_coexist',
        description: 'Ships can coexist with Ancient ships. Ancients in Draco-controlled sectors do not attack.',
        effectType: 'ancient_coexistence',
        params: {},
      },
      {
        id: 'draco_ancient_vp',
        description: '+1 VP per Ancient ship still on the board at end of game.',
        effectType: 'scoring_per_ancient',
        params: { vpPerAncient: 1 },
      },
    ],
    reputationSlots: [ReputationSlotType.Shared, ReputationSlotType.Shared, ReputationSlotType.Shared, ReputationSlotType.Shared],
    baseInitiativeOrder: 5,
  },

  [SpeciesId.Mechanema]: {
    id: SpeciesId.Mechanema,
    color: PlayerColor.White,
    name: 'Mechanema',
    subtitle: 'AI Builders',
    homeSectorId: '230',
    startingResources: {
      materials: 4,
      science: 3,
      money: 3,
    },
    startingStorage: {
      materials: 0,
      science: 0,
      money: 0,
    },
    tradeRate: 2,
    colonyShips: 3,
    influenceDiscs: 13,
    ambassadors: 3,
    startingTechs: ['positron_computer'],
    activationLimits: {
      [ActionType.Explore]: 1,
      [ActionType.Research]: 1,
      [ActionType.Upgrade]: 3,
      [ActionType.Build]: 3,
      [ActionType.Move]: 2,
      [ActionType.Influence]: 2,
    },
    startingFleet: [
      { shipType: ShipType.Interceptor, count: 1 },
    ],
    blueprintOverrides: {},
    buildingCosts: {
      [ShipType.Interceptor]: 2,
      [ShipType.Cruiser]: 4,
      [ShipType.Dreadnought]: 7,
      [ShipType.Starbase]: 2,
      orbital: 3,
      monolith: 8,
    },
    specialAbilities: [
      {
        id: 'mechanema_cheap_building',
        description: 'Reduced building costs: Interceptor 2, Cruiser 4, Dreadnought 7, Starbase 2, Orbital 3, Monolith 8.',
        effectType: 'building_cost_override',
        params: {},
      },
    ],
    reputationSlots: [ReputationSlotType.Shared, ReputationSlotType.Shared, ReputationSlotType.Shared, ReputationSlotType.Shared],
    baseInitiativeOrder: 2,
  },

  [SpeciesId.OrionHegemony]: {
    id: SpeciesId.OrionHegemony,
    color: PlayerColor.Black,
    name: 'Orion Hegemony',
    subtitle: 'Military Power',
    homeSectorId: '232',
    startingResources: {
      materials: 4,
      science: 3,
      money: 3,
    },
    startingStorage: {
      materials: 0,
      science: 0,
      money: 0,
    },
    tradeRate: 4,
    colonyShips: 3,
    influenceDiscs: 13,
    ambassadors: 3,
    startingTechs: ['neutron_bombs', 'gauss_shield_grid'],
    activationLimits: {
      [ActionType.Explore]: 1,
      [ActionType.Research]: 1,
      [ActionType.Upgrade]: 2,
      [ActionType.Build]: 2,
      [ActionType.Move]: 2,
      [ActionType.Influence]: 2,
    },
    startingFleet: [
      { shipType: ShipType.Cruiser, count: 1 },
    ],
    blueprintOverrides: {
      [ShipType.Interceptor]: {
        baseInitiative: 4,
        baseEnergy: 1,
        slots: [
          { slotType: ShipPartSlotType.Any, defaultPart: 'nuclear_source' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'nuclear_drive' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'ion_cannon' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'gauss_shield' },
        ],
      },
      [ShipType.Cruiser]: {
        baseInitiative: 3,
        baseEnergy: 1,
        slots: [
          { slotType: ShipPartSlotType.Any, defaultPart: 'nuclear_source' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'nuclear_drive' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'ion_cannon' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'electron_computer' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'hull' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'gauss_shield' },
        ],
      },
      [ShipType.Dreadnought]: {
        baseInitiative: 2,
        baseEnergy: 1,
        slots: [
          { slotType: ShipPartSlotType.Any, defaultPart: 'nuclear_source' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'nuclear_drive' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'ion_cannon' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'ion_cannon' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'electron_computer' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'hull' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'hull' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'gauss_shield' },
        ],
      },
      [ShipType.Starbase]: {
        slots: [
          { slotType: ShipPartSlotType.Any, defaultPart: 'ion_cannon' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'electron_computer' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'hull' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'hull' },
          { slotType: ShipPartSlotType.Any, defaultPart: 'gauss_shield' },
        ],
      },
    },
    buildingCosts: {
      [ShipType.Interceptor]: 3,
      [ShipType.Cruiser]: 5,
      [ShipType.Dreadnought]: 8,
      [ShipType.Starbase]: 3,
      orbital: 4,
      monolith: 10,
    },
    specialAbilities: [
      {
        id: 'orion_start_cruiser',
        description: 'Start with a Cruiser instead of an Interceptor.',
        effectType: 'starting_fleet_override',
        params: {},
      },
      {
        id: 'orion_high_initiative',
        description: 'All ship blueprints have increased initiative bonuses and additional energy.',
        effectType: 'initiative_modifier',
        params: {},
      },
    ],
    reputationSlots: [ReputationSlotType.Shared, ReputationSlotType.Shared, ReputationSlotType.Shared, ReputationSlotType.Shared, ReputationSlotType.Reputation],
    baseInitiativeOrder: 1,
  },
});

export const ALL_SPECIES: readonly SpeciesDefinition[] = Object.freeze(
  Object.values(SPECIES),
);
