import { TechCategory } from '../enums';
import type { TechDefinition } from '../types/tech';

export const MILITARY_TECHS: readonly TechDefinition[] = Object.freeze([
  {
    id: 'neutron_bombs',
    name: 'Neutron Bombs',
    category: TechCategory.Military,
    minCost: 2,
    maxCost: 2,
    trackPosition: 0,
    isRare: false,
    description: 'Allows destroying enemy population cubes after winning ground combat in a sector.',
    effect: { type: 'special', params: { ability: 'neutron_bombs' } },
  },
  {
    id: 'starbase_tech',
    name: 'Starbase',
    category: TechCategory.Military,
    minCost: 3,
    maxCost: 4,
    trackPosition: 1,
    unlocksBuilding: 'starbase',
    isRare: false,
    description: 'Unlocks the ability to build Starbase structures.',
  },
  {
    id: 'plasma_cannon',
    name: 'Plasma Cannon',
    category: TechCategory.Military,
    minCost: 4,
    maxCost: 6,
    trackPosition: 2,
    unlocksShipPart: 'plasma_cannon',
    isRare: false,
    description: 'Unlocks the Plasma Cannon ship part (2 orange dice, -2 energy).',
  },
  {
    id: 'phase_shield',
    name: 'Phase Shield',
    category: TechCategory.Military,
    minCost: 5,
    maxCost: 8,
    trackPosition: 3,
    unlocksShipPart: 'phase_shield',
    isRare: false,
    description: 'Unlocks the Phase Shield ship part (-2 to enemy hits, -1 energy).',
  },
  {
    id: 'advanced_mining',
    name: 'Advanced Mining',
    category: TechCategory.Military,
    minCost: 6,
    maxCost: 10,
    trackPosition: 4,
    isRare: false,
    description: 'Allows colonizing advanced materials population squares. Grants additional materials production.',
    effect: { type: 'advanced_colonize', params: { resourceType: 'materials' } },
  },
  {
    id: 'tachyon_source',
    name: 'Tachyon Source',
    category: TechCategory.Military,
    minCost: 6,
    maxCost: 12,
    trackPosition: 5,
    unlocksShipPart: 'tachyon_source',
    isRare: false,
    description: 'Unlocks the Tachyon Source ship part (+9 energy).',
  },
  {
    id: 'gluon_computer',
    name: 'Gluon Computer',
    category: TechCategory.Military,
    minCost: 7,
    maxCost: 14,
    trackPosition: 6,
    unlocksShipPart: 'gluon_computer',
    isRare: false,
    description: 'Unlocks the Gluon Computer ship part (+3 to hit, -2 energy).',
  },
  {
    id: 'plasma_missile',
    name: 'Plasma Missile',
    category: TechCategory.Military,
    minCost: 8,
    maxCost: 16,
    trackPosition: 7,
    unlocksShipPart: 'plasma_missile',
    isRare: false,
    description: 'Unlocks the Plasma Missile ship part (2 orange dice missile, -1 energy). Fires first in combat, one use.',
  },
]);

export const GRID_TECHS: readonly TechDefinition[] = Object.freeze([
  {
    id: 'gauss_shield_grid',
    name: 'Gauss Shield',
    category: TechCategory.Grid,
    minCost: 2,
    maxCost: 2,
    trackPosition: 0,
    unlocksShipPart: 'gauss_shield',
    isRare: false,
    description: 'Unlocks the Gauss Shield ship part.',
  },
  {
    id: 'fusion_source',
    name: 'Fusion Source',
    category: TechCategory.Grid,
    minCost: 3,
    maxCost: 4,
    trackPosition: 1,
    unlocksShipPart: 'fusion_source',
    isRare: false,
    description: 'Unlocks the Fusion Source ship part (+6 energy).',
  },
  {
    id: 'improved_hull',
    name: 'Improved Hull',
    category: TechCategory.Grid,
    minCost: 4,
    maxCost: 6,
    trackPosition: 2,
    unlocksShipPart: 'improved_hull',
    isRare: false,
    description: 'Unlocks the Improved Hull ship part (+2 hull, 0 energy).',
  },
  {
    id: 'positron_computer',
    name: 'Positron Computer',
    category: TechCategory.Grid,
    minCost: 5,
    maxCost: 8,
    trackPosition: 3,
    unlocksShipPart: 'positron_computer',
    isRare: false,
    description: 'Unlocks the Positron Computer ship part (+2 to hit, -1 energy).',
  },
  {
    id: 'advanced_economy',
    name: 'Advanced Economy',
    category: TechCategory.Grid,
    minCost: 6,
    maxCost: 10,
    trackPosition: 4,
    isRare: false,
    description: 'Allows colonizing advanced money population squares. Grants additional money production.',
    effect: { type: 'advanced_colonize', params: { resourceType: 'money' } },
  },
  {
    id: 'tachyon_drive',
    name: 'Tachyon Drive',
    category: TechCategory.Grid,
    minCost: 6,
    maxCost: 12,
    trackPosition: 5,
    unlocksShipPart: 'tachyon_drive',
    isRare: false,
    description: 'Unlocks the Tachyon Drive ship part (+3 movement, -3 energy).',
  },
  {
    id: 'antimatter_cannon',
    name: 'Antimatter Cannon',
    category: TechCategory.Grid,
    minCost: 7,
    maxCost: 14,
    trackPosition: 6,
    unlocksShipPart: 'antimatter_cannon',
    isRare: false,
    description: 'Unlocks the Antimatter Cannon ship part (2 blue dice, -4 energy).',
  },
  {
    id: 'quantum_grid',
    name: 'Quantum Grid',
    category: TechCategory.Grid,
    minCost: 8,
    maxCost: 16,
    trackPosition: 7,
    isRare: false,
    description: 'Immediately receive 2 additional Influence Discs, placed on your Influence Track.',
    effect: { type: 'instant_influence_discs', params: { count: 2 } },
  },
]);

export const NANO_TECHS: readonly TechDefinition[] = Object.freeze([
  {
    id: 'nanorobots',
    name: 'Nanorobots',
    category: TechCategory.Nano,
    minCost: 2,
    maxCost: 2,
    trackPosition: 0,
    isRare: false,
    description: 'You have one extra Activation when taking the Build Action.',
    effect: { type: 'extra_activation', params: { action: 'build', bonus: 1 } },
  },
  {
    id: 'fusion_drive',
    name: 'Fusion Drive',
    category: TechCategory.Nano,
    minCost: 3,
    maxCost: 4,
    trackPosition: 1,
    unlocksShipPart: 'fusion_drive',
    isRare: false,
    description: 'Unlocks the Fusion Drive ship part (+2 movement, -2 energy).',
  },
  {
    id: 'orbital_tech',
    name: 'Orbital',
    category: TechCategory.Nano,
    minCost: 4,
    maxCost: 6,
    trackPosition: 2,
    unlocksBuilding: 'orbital',
    isRare: false,
    description: 'Unlocks the ability to build Orbital structures (+1 money production).',
  },
  {
    id: 'advanced_robotics',
    name: 'Advanced Robotics',
    category: TechCategory.Nano,
    minCost: 5,
    maxCost: 8,
    trackPosition: 3,
    isRare: false,
    description: 'Immediately receive 1 additional Influence Disc, placed on your Influence Track.',
    effect: { type: 'instant_influence_discs', params: { count: 1 } },
  },
  {
    id: 'advanced_labs',
    name: 'Advanced Labs',
    category: TechCategory.Nano,
    minCost: 6,
    maxCost: 10,
    trackPosition: 4,
    isRare: false,
    description: 'You may place Population Cubes in Advanced Science Population Squares with your Colony Ships.',
    effect: { type: 'advanced_colonize', params: { resourceType: 'science' } },
  },
  {
    id: 'monolith_tech',
    name: 'Monolith',
    category: TechCategory.Nano,
    minCost: 6,
    maxCost: 12,
    trackPosition: 5,
    unlocksBuilding: 'monolith',
    isRare: false,
    description: 'Unlocks the ability to build Monolith structures (+3 VP each).',
  },
  {
    id: 'wormhole_generator',
    name: 'Wormhole Generator',
    category: TechCategory.Nano,
    minCost: 7,
    maxCost: 14,
    trackPosition: 6,
    isRare: false,
    description: 'You may Explore, Move to, and Influence adjacent Sectors if the edges connecting the Sectors contain at least one Wormhole (on either side).',
    effect: { type: 'special', params: { ability: 'wormhole_generator' } },
  },
  {
    id: 'artifact_key',
    name: 'Artifact Key',
    category: TechCategory.Nano,
    minCost: 8,
    maxCost: 16,
    trackPosition: 7,
    isRare: false,
    description: 'Instant: Gain 25 Resources, distributed in increments of 5 across Money, Materials, and Science.',
    effect: { type: 'instant_artifact_resources', params: { totalResources: 25, increment: 5 } },
  },
]);

export const RARE_TECHS: readonly TechDefinition[] = Object.freeze([
  {
    id: 'antimatter_splitter',
    name: 'Antimatter Splitter',
    category: TechCategory.Rare,
    minCost: 5,
    maxCost: 5,
    isRare: true,
    description: 'After a battle round, you may split damage across multiple enemy ships instead of concentrating on one.',
    effect: { type: 'special', params: { ability: 'antimatter_splitter' } },
  },
  {
    id: 'conifold_field',
    name: 'Conifold Field',
    category: TechCategory.Rare,
    minCost: 5,
    maxCost: 5,
    unlocksShipPart: 'conifold_field',
    isRare: true,
    description: 'Unlocks the Conifold Field ship part (-4 to enemy hits, -2 energy).',
  },
  {
    id: 'neutron_absorber',
    name: 'Neutron Absorber',
    category: TechCategory.Rare,
    minCost: 5,
    maxCost: 5,
    isRare: true,
    description: 'Your population cubes cannot be removed by Neutron Bombs.',
    effect: { type: 'special', params: { ability: 'neutron_absorber' } },
  },
  {
    id: 'absorption_shield',
    name: 'Absorption Shield',
    category: TechCategory.Rare,
    minCost: 6,
    maxCost: 7,
    unlocksShipPart: 'absorption_shield',
    isRare: true,
    description: 'Unlocks the Absorption Shield ship part (-3 to enemy hits, -2 energy).',
  },
  {
    id: 'cloaking_device',
    name: 'Cloaking Device',
    category: TechCategory.Rare,
    minCost: 6,
    maxCost: 7,
    isRare: true,
    description: 'Each of your Ships requires a dedicated enemy Ship to Pin it. Moving through opponent Sectors is not an Act of Aggression if your Ships remain Unpinned.',
    effect: { type: 'special', params: { ability: 'cloaking_device' } },
  },
  {
    id: 'improved_logistics',
    name: 'Improved Logistics',
    category: TechCategory.Rare,
    minCost: 6,
    maxCost: 7,
    isRare: true,
    description: 'Gain 1 additional Move Activation during each Move Action you take.',
    effect: { type: 'extra_activation', params: { action: 'move', bonus: 1 } },
  },
  {
    id: 'sentient_hull',
    name: 'Sentient Hull',
    category: TechCategory.Rare,
    minCost: 6,
    maxCost: 7,
    unlocksShipPart: 'sentient_hull',
    isRare: true,
    description: 'Unlocks the Sentient Hull ship part (+3 hull, -1 energy).',
  },
  {
    id: 'soliton_cannon',
    name: 'Soliton Cannon',
    category: TechCategory.Rare,
    minCost: 7,
    maxCost: 9,
    unlocksShipPart: 'soliton_cannon',
    isRare: true,
    description: 'Unlocks the Soliton Cannon ship part (1 red die, -3 energy).',
  },
  {
    id: 'transition_drive',
    name: 'Transition Drive',
    category: TechCategory.Rare,
    minCost: 7,
    maxCost: 9,
    unlocksShipPart: 'transition_drive',
    isRare: true,
    description: 'Unlocks the Transition Drive ship part (+3 movement, -1 energy).',
  },
  {
    id: 'warp_portal',
    name: 'Warp Portal',
    category: TechCategory.Rare,
    minCost: 7,
    maxCost: 9,
    isRare: true,
    description: 'Immediately place the Warp Portal Tile on any Sector you Control. The Warp Portal connects this Sector to all other Warp Portal Sectors. Worth 1 VP if Controlled at end of game.',
    effect: { type: 'instant_warp_portal', params: { vp: 1 } },
  },
  {
    id: 'flux_missile',
    name: 'Flux Missile',
    category: TechCategory.Rare,
    minCost: 8,
    maxCost: 11,
    unlocksShipPart: 'flux_missile',
    isRare: true,
    description: 'Unlocks the Flux Missile ship part (2 blue dice missile, -2 energy).',
  },
  {
    id: 'pico_modulator',
    name: 'Pico Modulator',
    category: TechCategory.Rare,
    minCost: 8,
    maxCost: 11,
    isRare: true,
    description: 'Gain 2 additional Upgrade Activations during each Upgrade Action you take.',
    effect: { type: 'extra_activation', params: { action: 'upgrade', bonus: 2 } },
  },
  {
    id: 'ancient_labs',
    name: 'Ancient Labs',
    category: TechCategory.Rare,
    minCost: 9,
    maxCost: 13,
    isRare: true,
    description: 'Instant: Immediately draw and resolve one Discovery Tile.',
    effect: { type: 'instant_discovery_draw', params: { count: 1 } },
  },
  {
    id: 'zero_point_source',
    name: 'Zero-Point Source',
    category: TechCategory.Rare,
    minCost: 10,
    maxCost: 15,
    unlocksShipPart: 'zero_point_source',
    isRare: true,
    description: 'Unlocks the Zero-Point Source ship part (+12 energy).',
  },
  {
    id: 'metasynthesis',
    name: 'Metasynthesis',
    category: TechCategory.Rare,
    minCost: 11,
    maxCost: 17,
    isRare: true,
    description: 'You may place Population Cubes in any Advanced Population Squares with your Colony Ships (all types: Materials, Science, Money).',
    effect: { type: 'advanced_colonize_all', params: {} },
  },
]);

export const ALL_TECHS: readonly TechDefinition[] = Object.freeze([
  ...MILITARY_TECHS,
  ...GRID_TECHS,
  ...NANO_TECHS,
  ...RARE_TECHS,
]);

export const TECHS_BY_ID: Readonly<Record<string, TechDefinition>> = Object.freeze(
  Object.fromEntries(ALL_TECHS.map((t) => [t.id, t])),
);
