// Extracted from public_catann/catann_files/shared.a1f7aa47ccdd213a17fe.js
// and public_catann/catann_files/ui-game.7cbf53940f4f50959d28.js.
// and public_catann/catann_files/web.d88224967e857de5296c.js.

export enum SocketRouteType {
  RouteToServerType = 2,
  RouteToServerDirect = 3,
  SocketRouter = 4,
}

export enum GameAction {
  GameChatSubmit = 0,
  SkippedWelcome = 1,
  ClickedDice = 2,
  SelectedTile = 3,
  SelectedTiles = 4,
  SelectedPlayer = 5,
  PassedTurn = 6,
  SelectedCards = 7,
  SelectedCardsState = 8,
  BuyDevelopmentCard = 9,
  WantToBuildRoad = 10,
  ConfirmBuildRoad = 11,
  ConfirmBuildRoadSkippingSelection = 12,
  ConfirmRemoveRoad = 13,
  WantToBuildSettlement = 14,
  ConfirmBuildSettlement = 15,
  ConfirmBuildSettlementSkippingSelection = 16,
  WantToBuildCity = 17,
  ConfirmBuildCity = 18,
  ConfirmBuildCitySkippingSelection = 19,
  WantToBuildShip = 20,
  ConfirmBuildShip = 21,
  ConfirmBuildShipSkippingSelection = 22,
  WantToMoveShip = 23,
  SelectedShipToMove = 24,
  ConfirmMoveShip = 25,
  WantToBuildCityWall = 26,
  ConfirmBuildCityWall = 27,
  ConfirmBuildCityWallSkippingSelection = 28,
  WantToPlaceKnight = 29,
  ConfirmPlaceKnight = 30,
  ConfirmPlaceKnightSkippingSelection = 31,
  WantToUpgradeKnight = 32,
  ConfirmUpgradeKnight = 33,
  ConfirmUpgradeKnightSkippingSelection = 34,
  WantToActivateKnight = 35,
  ConfirmActivateKnight = 36,
  ConfirmActivateKnightSkippingSelection = 37,
  WantToTakeKnightAction = 38,
  SelectKnightToTakeAction = 39,
  ConfirmMoveKnight = 40,
  ConfirmMoveKnightOffTurn = 41,
  ConfirmRemoveKnight = 42,
  ConfirmCityUpgrade = 43,
  ConfirmBuildMetropolis = 44,
  ConfirmPillageCity = 45,
  ConfirmDicePair = 46,
  PreCreateTrade = 47,
  ClickedDevelopmentCard = 48,
  CreateTrade = 49,
  UpdateTradeResponse = 50,
  ExecuteTrade = 51,
  ToggledEmbargo = 52,
  PlayDevelopmentCardFromHand = 53,
  TogglePause = 54,
  LeaveGame = 55,
  Resign = 56,
  RequestSpecialBuildPhase = 57,
  CancelSpecialBuildPhase = 58,
  ClickedRematch = 59,
  Vote = 60,
  Pong = 61,
  RequestBeginnerHint = 62,
  SkipWelcomeAction = 63,
  RequestBeginnerModeLevelEnd = 64,
  StressTestGracefulShutdown = 65,
  SelectedInitialPlacementIndex = 66,
  RequestGameState = 67,
  NotifyBackendClientAutoReconnected = 68,
  ReportPlayer = 69,
}

export enum State {
  GameStateUpdate = 130,
  MatchmakingStateUpdate = 131,
  LobbyStateUpdate = 133,
  ChannelStateUpdate = 134,
  GeneralStateUpdate = 135,
  SocketMonitorUpdate = 136,
  RoomEvent = 137,
  SocketEvent = 138,
  ShuffleStateUpdate = 139,
}

export enum MatchmakingState {
  MatchmakingUpdate = 1,
  MatchmakingError = 2,
  MatchmakingShowPreRollAd = 3,
  MatchmakingDisableAdblock = 4,
  MatchmakingReconnect = 5,
}

export enum ShuffleState {
  ShuffleQueueData = 1,
  ShufflePlayerData = 2,
}

export enum GeneralState {
  UpdateOnlineStatus = 1,
  ReceivedRoomInvites = 2,
  RoomInviteResponse = 3,
  RemoveRoomInvite = 4,
  RoomInviteSentSuccessfully = 5,
  Notifications = 6,
  MarkedAsRead = 7,
  ReceivedFriendRequest = 8,
}

export enum ChannelState {
  ChannelRoomUpdate = 1,
}

export enum UIGameEventEnums {
  FinishedBuildingGame = 0,
  GameStateUpdated = 1,
  PlayerControllerStateUpdated = 2,
  DiceStateUpdated = 3,
  BankStateUpdated = 4,
  BankTradeRatioStateUpdated = 5,
  MapStateUpdated = 6,
  KarmaUpdated = 7,
  CanResign = 8,
  AmountOfCardsToDiscardUpdated = 9,
  AmountOfCardsToSelect = 10,
  SelectCardsToDiscard = 11,
  SelectCardsFromBankUsingDevelopmentCard = 12,
  SelectCardsForPendingDistribution = 13,
  SelectCardToGiveToAnotherPlayer = 14,
  ConfirmUseDevelopmentCard = 15,
  StealDevelopmentCardFromPlayer = 16,
  StealResourceCardFromPlayer = 17,
  SelectPlayer = 18,
  SelectPlayerForDevelopmentCard = 19,
  SelectPlayerAndCard = 20,
  SelectDice = 21,
  GivePlayerCardFromTile = 22,
  ExchangeCards = 23,
  GivePlayerGrantedCards = 24,
  CloseTradeUI = 25,
  ShowTradeUI = 26,
  TradeStateUpdated = 27,
  EmbargoStatusUpdated = 28,
  RemoveTradeOffer = 29,
  TradeResetStateAtEndOfTurn = 30,
  TradeResponseState = 31,
  NewTradeOfferReceived = 32,
  TradePlayersCreatingCounterOfferState = 33,
  BoldTextInTradeWindow = 34,
  CloseDiscardCardUI = 35,
  ShowDiscardCardUI = 36,
  ClosePopupUI = 37,
  SpecialBuildPhaseStateUpdated = 38,
  SetRoadEdgeHighlight = 39,
  SetShipEdgeHighlight = 40,
  SetCornerHighlight = 41,
  SetTileHighlight = 42,
  HighlightDiceNumbersForInventor = 43,
  VoteReceived = 44,
  PlayerReceivedAchievement = 45,
  CanvasResized = 46,
  ClickedMultiButton = 47,
  SpectatorDataUpdated = 48,
  KnightStateUpdated = 49,
  CityImprovementStateReceived = 50,
  CityImprovementStateUpdated = 51,
  ForceShowCityImprovementButtons = 52,
  MerchantStateUpdated = 53,
  GameEnd = 54,
  GameEndRematchTextUpdated = 55,
  GameEndShowMap = 56,
  GameEndHideMap = 57,
  HoveredOverPlayerInformationArrow = 58,
  PointerOutPlayerInformationView = 59,
  RobberMoved = 60,
  MerchantBankTradeRatioActive = 61,
  GamePauseToggled = 62,
  ToggleChatFeed = 63,
  ToggleLogFeed = 64,
  NewChatMessageReceived = 65,
  TemporaryPlayerStuckInEmbargoState = 66,
  BeginnerHintReceived = 67,
  HighlightTradeOffer = 68,
  PopupActive = 69,
  FeedbackFormSubmitted = 70,
  FloatingNotification = 71,
  BeginnerModeStart = 72,
  BeginnerModeInteractWithGuide = 73,
  BeginnerModeForceOpenGuideBubble = 74,
  BeginnerModeActionUpdated = 75,
  BeginnerModeLevelEnd = 76,
  GameInformationPopupActive = 77,
  BeginnerModeClickedDisabledElement = 78,
  SuggestAction = 79,
  SelectDiceNumbersConfirmation = 80,
  DiceNumberAnimationEnd = 81,
  TileNumberAnimationEnd = 82,
  CardAnimationEnd = 83,
  ReplayModeStart = 84,
  PlayerInformationViewClicked = 85,
  ClientReconnectionTriggered = 86,
  EndOfInitialPlacement = 87,
  GameVisibilityUpdated = 88,
}

export enum RoomJoinStatus {
  Joined = 0,
  CannotJoinKicked = 1,
  CannotJoinFull = 2,
  CannotJoinKarma = 3,
}

export enum ChannelStatus {
  Game = 0,
  Room = 1,
  Closed = 2,
  Reconnect = 3,
}

export enum RoomInfoMessage {
  None = 0,
  ClickReady = 1,
  PremiumItemSelected = 2,
}

export enum AudioEvent {
  DiceRoll1 = 0,
  DiceRoll2 = 1,
  DiceRoll3 = 2,
  DiceRoll4 = 3,
  YourTurn = 4,
  FirstReminder = 5,
  RoadPlace = 6,
  SettlementPlace = 7,
  CityPlace = 8,
  ShipPlace = 9,
  ShipMove = 10,
  MetropolisPlace = 11,
  CityWallPlace = 12,
  CityDestroy = 13,
  CityImprovement = 14,
  RobberPlace = 15,
  PiratePlace = 16,
  LeaveRoom = 17,
  JoinRoom = 18,
  RoomSettingUpdated = 19,
  RoomGetReady = 20,
  ClockTick = 21,
  MessageNotification = 22,
  Click = 23,
  Victory = 24,
  VoteReminder = 25,
  AchievementCKProgress = 26,
  GameStarted = 27,
  GameStartedGuitar = 28,
  AchievementLargestArmy = 29,
  AchievementLongestRoad = 30,
  SettlementPhaseEnded = 31,
  SettlementPhaseEndedGuitar = 32,
  OfferAcceptable = 33,
  OfferNotAcceptable = 34,
  OfferAccepted = 35,
  OfferRejected = 36,
  Reconnect = 37,
  Disconnect = 38,
  KnightEquip = 39,
  KnightPlace = 40,
  KnightUpgrade = 41,
  DiscardBroadcast = 42,
  DiscardNotification = 43,
  BeginnerHintActivated = 44,
  DevelopmentCardBought = 45,
  DevelopmentCardMonopoly = 46,
  DevelopmentCardUsed = 47,
}

export enum TradeResponseStatus {
  PendingResponse = 0,
  Accepted = 1,
  Rejected = 2,
  Embargoed = 3,
}

export enum PlayerColor {
  None = 0,
  Red = 1,
  Blue = 2,
  Orange = 3,
  Green = 4,
  Black = 5,
  Bronze = 6,
  Silver = 7,
  Gold = 8,
  White = 9,
  Purple = 10,
  MysticBlue = 11,
  Pink = 12,
}

export enum VictoryPointSource {
  Settlement = 0,
  City = 1,
  DevelopmentCardVictoryPoint = 2,
  LargestArmy = 3,
  LongestRoad = 4,
  Chits = 5,
  Metropolis = 6,
  DefenderOfColonist = 7,
  ProgressCardVictoryPoint = 8,
  Merchant = 9,
}

export enum MapPieceType {
  Road = 0,
  Ship = 1,
  Settlement = 2,
  City = 3,
  CityWall = 4,
  Robber = 5,
  Pirate = 6,
}

export enum AchievementType {
  LongestRoad = 0,
  LargestArmy = 1,
}

export enum GameLogMessageType {
  PlayerReconnecting = 0,
  BoughtDevelopmentCard = 1,
  WelcomeMessage = 2,
  StartedSpectating = 3,
  PlayerPlacedPiece = 4,
  BuiltPiece = 5,
  PlayerMovedPiece = 6,
  UpgradedKnight = 7,
  ActivatedKnight = 8,
  RemovedKnight = 9,
  RolledDice = 10,
  MovedRobber = 11,
  PlacedMetropolis = 12,
  ReceivedCard = 13,
  StolenResourceCardThief = 14,
  StolenResourceCardVictim = 15,
  StolenResourceCardClosed = 16,
  StolenDevelopmentCardThief = 17,
  StolenDevelopmentCardVictim = 18,
  StolenDevelopmentCardClosed = 19,
  PlayerPlayedDevelopmentCard = 20,
  YearOfPlentyTookFromBank = 21,
  LeftTheGame = 22,
  WasInactiveAndKicked = 23,
  Disconnected = 24,
  StoppedSpectating = 25,
  KarmaPenaltyRemoved = 26,
  KarmaSystemDisabledDueToPlayersLeaving = 27,
  KarmaSystemInactiveCannotVoteToDisable = 28,
  KarmaSystemIsAlreadyDisabled = 29,
  YouCantStartVoteBecauseYouAreTheOnlyPlayerLeft = 30,
  YouCantStartVoteDueToYourLeaverStatus = 31,
  YouCanOnlyStartAVoteToDisableKarmaOnce = 32,
  KarmaSystemVoteToDisableSucceeded = 33,
  KarmaSystemVoteToDisableDeclined = 34,
  ThereIsAlreadyAnActiveVote = 35,
  PlayerStartedAVoteToDisableKarma = 36,
  GameEndMessage = 37,
  GameEndChatDisabled = 38,
  PlayerCouldNotStealFrom = 39,
  GameCrashedZero = 40,
  GameCrashedOne = 41,
  GameCrashedTwo = 42,
  GameCrashedThree = 43,
  Separator = 44,
  PlayerWonTheGame = 45,
  GameEndedDueToServerRestart = 46,
  ResourceDistribution = 47,
  NotEnoughCardsInBankToDistribute = 48,
  TileBlockedByRobber = 49,
  PlayersSelectingResourcesFromAqueduct = 50,
  BotSelectingAqueductResourcesFor = 51,
  NotEnoughProgressCardsInBankToDistribute = 52,
  PlayersDiscardingProgressCards = 53,
  PlayerDiscarded = 55,
  PlayersSelectingResourceFromGoldTile = 56,
  FriendlyPirateActive = 57,
  BotIsSelectingWhereToPlacePieceFor = 58,
  RobberDisabledUntilFirstBarbarianAttack = 59,
  FriendlyRobberActive = 60,
  LostMetropolis = 61,
  PlayerUpgradedImprovementTo = 62,
  BotIsSelectingGoldTileResourceFor = 63,
  BotIsSelectingCardsToDiscardFor = 64,
  PlayerSettledOnForeignLand = 65,
  PlayerReceivedAchievement = 66,
  PlayerLostAchievement = 67,
  PlayerPassedAchievementTo = 68,
  PlayerMovedMerchantTo = 69,
  PlayerLostPossessionOfMerchant = 70,
  BotIsSelectingWhereToPlaceMerchantFor = 71,
  BotIsPlacing = 72,
  BotIsSelectingWhoToRobFor = 73,
  NoPlayerToStealFrom = 74,
  SkippingSpecialBuildPhase = 75,
  PlayerEnteredSpecialBuildPhase = 76,
  BotIsSelectingProgressCardFor = 77,
  PlayerIsSpyingPlayer = 78,
  PlayersDefeatedBarbarians = 79,
  PlayerAwardedDefenderOfColonist = 80,
  PlayersSelectingProgressCard = 81,
  BotIsSelectingPieceToDestroyFor = 82,
  BarbariansAttackedButNoCityToPillage = 83,
  PlayersDefeatedByBarbarians = 84,
  PlayersPieceDestroyedByBarbarians = 85,
  PlayerStoleUsingMonopoly = 86,
  BotIsPlacingPieceFor = 87,
  BotIsSelectingWhereToPlaceKnightFor = 88,
  PlayerUsedPieceToMovePiece = 89,
  PlayerDisplacedPiece = 90,
  BotSelectingWhereToMoveKnightFor = 91,
  PlayerRemovedPlayersKnight = 92,
  BotSelectingKnightToRemoveFor = 93,
  BotSelectingKnightToUpgradeFor = 94,
  PlayerReceivedVPProgressCard = 95,
  PlayerSelectedPlayer = 96,
  PlayerRepositioningEdgePiece = 97,
  PlayerRemovedEdgePiece = 98,
  BotIsSelectingEdgePieceToRemoveFor = 99,
  BotSelectingResourcesFor = 100,
  BotSelectingDiceFor = 101,
  PlayerSwappedTileNumbers = 102,
  ExchangedCardsThief = 103,
  ExchangedCardsVictim = 104,
  ExchangedCardsClosed = 105,
  PlayerIsStealingFrom = 106,
  PlayerSelectedCard = 107,
  BotLogicNotSupportedForCitiesAndKnights = 108,
  PlayerUnlockedAqueduct = 109,
  PlayerUnlockedTradingHouse = 110,
  PlayerUnlockedFortress = 111,
  PlayerResigned = 112,
  PlayerStartedEmbargo = 113,
  PlayerEndedEmbargo = 114,
  PlayerTradedWithPlayer = 115,
  PlayerTradedWithBank = 116,
  PlayerWantsToCounterOfferWith = 117,
  PlayerWantsToTradeWith = 118,
  PlayerCreatedRematch = 119,
  PlayersJoinedRematch = 120,
  YouCanOnlyStartAVoteToPauseXTimes = 121,
  GamePaused = 122,
  GameResumed = 123,
  PauseSystemPlayerStartedVotePause = 124,
  PauseSystemPlayerStartedVoteResume = 125,
  PauseSystemVoteSucceededPause = 126,
  PauseSystemVoteSucceededResume = 127,
  PauseSystemVoteDeclinedPause = 128,
  PauseSystemVoteDeclinedResume = 129,
  YouAreLastPlayerYouWillWinIfOpponentDoesNotReconnect = 130,
  VoteHasBeenCanceledBecauseGameEnded = 131,
  PlayerPlacedKnight = 132,
  PlayerMovedKnight = 133,
  ChatCommandGetAllResources = 134,
  ChatCommandGetCard = 135,
  ChatCommandRollAll = 136,
  ChatCommandRollDice = 137,
  ChatCommandRollNextDice = 138,
  CantStealPlayersDontHaveCards = 139,
  PermanentlyKickedForGoingAFKTooManyTime = 140,
  DiceRolledAutomatically = 141,
}

export enum GamePhase {
  InitialPlacement = 0,
  Dice = 1,
  Turn = 2,
  GameEnd = 3,
  SpecialBuildPhase = 4,
}

export enum PlayerActionState {
  None = 0,
  InitialPlacementPlaceSettlement = 1,
  InitialPlacementPlaceCity = 2,
  InitialPlacementRoadPlacement = 3,
  PlaceRoad = 4,
  PlaceRoadForFree = 5,
  PlaceSettlement = 6,
  PlaceCity = 7,
  PlaceCityWithDiscount = 8,
  PlaceShip = 9,
  PlaceShipForFree = 10,
  SelectShipToMove = 11,
  MoveShip = 12,
  PlaceCityWall = 13,
  PlaceCityWallForFree = 14,
  PlaceKnight = 15,
  PlaceKnightForFree = 16,
  UpgradeKnight = 17,
  UpgradeKnightForFree = 18,
  ActivateKnight = 19,
  SelectKnightToTakeAction = 20,
  SelectKnightAction = 21,
  MoveKnightOffTurn = 22,
  SelectKnightToRemove = 23,
  PlaceRobberOrPirate = 24,
  PlaceRobberOnly = 25,
  PlacePirateOnly = 26,
  SelectWhoToRob = 27,
  SelectCardsToDiscard = 28,
  SelectProgressCardsToDiscard = 29,
  Place2MoreRoadBuilding = 30,
  Place1MoreRoadBuilding = 31,
  Select2ResourcesForYearOfPlenty = 32,
  Select1ResourceForMonopoly = 33,
  SelectCardsForPendingDistributions = 34,
  PlaceMetropolis = 35,
  SelectProgressCard = 36,
  SelectCityToPillage = 37,
  PlaceMerchant = 38,
  SelectDiceForAlchemist = 39,
  SelectTileProductionNumbersToSwap = 40,
  SelectPlayerForDeserter = 41,
  SelectRoadToRemove = 42,
  DiplomatSelectWhetherToPlaceNewEdgePiece = 43,
  IntrigueSelectKnightToMove = 44,
  SpySelectPlayer = 45,
  SpySelectProgressCard = 46,
  SelectCardsForWedding = 47,
  CommercialHarborSelectPlayerAndResource = 48,
  CommercialHarborOpponentSelectsCard = 49,
  MasterMerchantSelectPlayer = 50,
  MasterMerchantSelectCards = 51,
  MerchantFleetSelectResource = 52,
  ResourceMonopolySelectResource = 53,
  CommodityMonopolySelectResource = 54,
}

export enum TileType {
  Desert = 0,
  Lumber = 1,
  Brick = 2,
  Wool = 3,
  Grain = 4,
  Ore = 5,
  Gold = 6,
  Fog = 7,
  Sea = 8,
}

export enum EdgeDirection {
  NorthWest = 0,
  West = 1,
  SouthWest = 2,
}

export enum EdgePieceType {
  Road = 1,
  Ship = 2,
}

export enum CornerDirection {
  North = 0,
  South = 1,
}

export enum CornerPieceType {
  Settlement = 1,
  City = 2,
  DestroyedCity = 3,
  KnightActiveLevel1 = 4,
  KnightActiveLevel2 = 5,
  KnightActiveLevel3 = 6,
  KnightInactiveLevel1 = 7,
  KnightInactiveLevel2 = 8,
  KnightInactiveLevel3 = 9,
}

export enum SpecialBuildingType {
  IslandSettlingChits = 0,
  CityWall = 1,
  MetropolisScience = 2,
  MetropolisTrade = 3,
  MetropolisPolitics = 4,
}

export enum PortType {
  Port = 1,
  PortLumber = 2,
  PortBrick = 3,
  PortWool = 4,
  PortGrain = 5,
  PortOre = 6,
}

export enum CardEnum {
  ResourceBack = 0,
  Lumber = 1,
  Brick = 2,
  Wool = 3,
  Grain = 4,
  Ore = 5,
  Cloth = 6,
  Coin = 7,
  Paper = 8,
  AnyResource = 9,
  DevelopmentBack = 10,
  Knight = 11,
  VictoryPoint = 12,
  Monopoly = 13,
  RoadBuilding = 14,
  YearOfPlenty = 15,
  CommodityBack = 16,
  ProgressCardTradeBack = 17,
  ProgressCardTradeCommercialHarbor = 18,
  ProgressCardTradeMasterMerchant = 19,
  ProgressCardTradeMerchant = 20,
  ProgressCardTradeMerchantFleet = 21,
  ProgressCardTradeResourceMonopoly = 22,
  ProgressCardTradeCommodityMonopoly = 23,
  ProgressCardPoliticsBack = 24,
  ProgressCardPoliticsBishop = 25,
  ProgressCardPoliticsConstitution = 26,
  ProgressCardPoliticsDeserter = 27,
  ProgressCardPoliticsDiplomat = 28,
  ProgressCardPoliticsIntrigue = 29,
  ProgressCardPoliticsSaboteur = 30,
  ProgressCardPoliticsSpy = 31,
  ProgressCardPoliticsWarlord = 32,
  ProgressCardPoliticsWedding = 33,
  ProgressCardScienceBack = 34,
  ProgressCardScienceAlchemist = 35,
  ProgressCardScienceCrane = 36,
  ProgressCardScienceEngineer = 37,
  ProgressCardScienceInventor = 38,
  ProgressCardScienceIrrigation = 39,
  ProgressCardScienceMedicine = 40,
  ProgressCardScienceMining = 41,
  ProgressCardSciencePrinter = 42,
  ProgressCardScienceRoadBuilding = 43,
  ProgressCardScienceSmith = 44,
  ProgressCardBack = 45,
  ResourceOverLimit = 46,
}

export enum CardType {
  Resource = 0,
  Commodity = 1,
  AnyResource = 2,
  Development = 3,
  ProgressTrade = 4,
  ProgressPolitics = 5,
  ProgressScience = 6,
  Miscellaneous = 7,
}

export enum ResourceSelectionReason {
  StartingResources = 0,
  ResourceTile = 1,
  GoldTile = 2,
  Aqueduct = 3,
  BarbarianProgressCard = 4,
}

export enum PlayerTitleType {
  Monopolist = 0,
  Juggernaut = 1,
}

export enum CityImprovementType {
  Trade = 0,
  Politics = 1,
  Science = 2,
}

export enum ChatMessageType {
  Message = 0,
  SystemMessage = 1,
  UnableToSend = 2,
  ChatDisabled = 3,
  ChatEnabled = 4,
  BadLanguage = 5,
  TooLong = 6,
  Spam = 7,
  WrongCommand = 8,
  CommandCrashed = 9,
  GameCommandOnly = 10,
  EmojiTutorial = 11,
  CommandTutorial = 12,
  DisableKarmaTutorial = 13,
  PauseGameTutorial = 14,
  SpectatorCannotSendMessage = 15,
  YouAreMuted = 16,
  AdminKickedPlayer = 17,
  CanOnlyResignIn1v1 = 18,
}

export enum GameStateUpdateType {
  FirstGameState = 1,
  BuildGame = 4,
  TogglePauseGame = 5,
  CanResignGame = 6,
  PlayerControllerState = 12,
  AmountOfCardsToDiscard = 13,
  CardsToSelectForDevelopmentCard = 18,
  CardsToSelectForPendingTransaction = 19,
  SelectPlayerUsingDevelopmentCard = 20,
  ConfirmUseDevelopmentCard = 21,
  StealDevelopmentCardFromPlayer = 22,
  StealResourceCardFromPlayer = 23,
  SelectPlayerAndCard = 24,
  SelectCardsToGiveToPlayer = 25,
  SelectDice = 26,
  ClosePopupUI = 27,
  GivePlayerResourcesFromTile = 28,
  SelectPlayer = 29,
  HighlightCorners = 30,
  HighlightRoadEdges = 31,
  HighlightShipEdges = 32,
  HighlightTiles = 33,
  HighlightDiceNumbersForInventor = 34,
  TradeState = 36,
  TradeResponseState = 37,
  EmbargoState = 38,
  BoldTextInTradeWindow = 39,
  CloseOffer = 40,
  InfoMessage = 42,
  ExchangeCards = 43,
  GameSettings = 44,
  GameEndState = 45,
  RematchLink = 46,
  EndGameText = 47,
  SpectatorData = 48,
  Vote = 51,
  CityImprovementStateUpdated = 52,
  ForceShowCityImprovementButtons = 53,
  MerchantStateUpdates = 58,
  PlayTurnSound = 59,
  PlayersTakingAction = 60,
  PlayersDoneTakingAction = 61,
  ExitInitialPlacement = 62,
  TradeFinalized = 63,
  TradeRejectedByAll = 64,
  KnightPlaced = 65,
  KnightActivated = 66,
  KnightUpgraded = 67,
  PlayerDisconnected = 68,
  PlayerReconnected = 69,
  DiscardBroadcast = 70,
  SpectatorChatMessage = 73,
  SendBroadcast = 74,
  TradeEmbargoState = 75,
  Ping = 76,
  BeginnerHintActivated = 77,
  KarmaState = 78,
  StressTestLagTest = 79,
  ResetTradeStateAtEndOfTurn = 80,
  ClosedTradeStates = 81,
  BeginnerModeActionUpdate = 87,
  BeginnerModeLevelEnd = 88,
  ResetBeginnerModeLevel = 89,
  TriggerClientGameStateReset = 90,
  GameStateUpdated = 91,
  ReplayData = 92,
  EndOfInitialPlacement = 93,
}

export enum ServerActionType {
  GameAction = 1,
  LobbyAction = 2,
  RoomAction = 3,
  MatchmakingAction = 4,
  ChannelAction = 5,
  Noop = 6,
  GeneralAction = 7,
  Echo = 8,
  CloseSocket = 9,
  RoomCommand = 10,
  ShuffleAction = 11,
}

export enum LobbyAction {
  ClickedBotGame = 2,
  ClickedCreateRoom = 3,
  ClickedJoinRoom = 4,
  AccessGameLink = 5,
  ClickedSpectateGame = 6,
  ReconnectGame = 7,
  SaveClientReferrer = 8,
  SetAdBlockStatus = 9,
  InteractedWithSite = 10,
  ClickedStartBeginnerMode = 11,
  Clicked1v1BeginnerBotGame = 12,
  ClickedEasyBotGame = 13,
  WatchRoomList = 14,
  StopWatchingRoomList = 15,
  AutoRejoinGame = 16,
}

export enum LobbyState {
  AutoRejoinGame = 1,
  SessionState = 2,
  UserStateUpdate = 3,
  LobbyDisconnectData = 4,
  SendPopup = 5,
  ShowCornerPopup = 6,
  SendBroadcast = 7,
  SocketTest = 8,
  ServerUpdating = 9,
  ReloadClient = 10,
  ServerUpdated = 11,
  RoomListUpdate = 12,
}

export enum ChannelAction {
  ChannelJoin = 1,
  ChannelJoinRoomOrGame = 2,
}

export enum MatchmakingAction {
  ClickedFindGame = 1,
  ClickedCancelFindGame = 2,
}

export enum GeneralAction {
  RegisterToFriendService = 1,
  ChangeOnlineStatus = 2,
  GetAllFriendsOnlineStatus = 3,
  InviteFriendToRoom = 4,
  GetAllRoomInvitesReceived = 5,
  RespondToFriendRoomInvite = 6,
  GetNotifications = 7,
  MarkNotificationAsRead = 8,
  MarkAllNotificationsAsRead = 9,
  RegisterToNotificationService = 10,
}

export enum OnlineStatus {
  Offline = 0,
  OnlineAndIdle = 1,
  InRoom = 2,
  InGame = 3,
}

export enum RoomCreationType {
  Standard = 0,
  FreeMap = 1,
  BeginnerMode = 2,
  CustomLink = 3,
  DiscordActivity = 4,
  Tournament = 5,
}

export enum RoomSettingEditType {
  EditSettings = 0,
  SeedOrderSelection = 1,
  PlayOrderSelection = 2,
}

export enum ShuffleQueueAction {
  GetShuffleQueueData = 1,
}

export enum DiscordActivityCommand {
  ContentFrameReady = "content-frame-ready",
  Subscribe = "subscribe",
  Unsubscribe = "unsubscribe",
  SetActivity = "set-activity",
  DispatchDiscordEvent = "dispatch",
  OpenExternalLink = "open-external-link",
  InviteFriends = "invite-friends",
  Purchase = "purchase",
  ShareMoment = "share-moment",
  ShareActivityLink = "share-activity-link",
  SetOrientation = "set-orientation",
}

export enum DiscordActivityEvent {
  Ready = "ready",
  CreateMountPopup = "create-mount-popup",
}

export enum DiscordActivityError {
  UserAlreadyHasMembershipError = "user-already-has-membership-error",
}

export enum DiscordActivityPurchaseAction {
  PurchaseMembership = 0,
  PurchaseGift = 1,
  PurchaseCoins = 2,
  InviteFriends = 3,
  ShareMoment = 4,
  OpenExternalLink = 5,
  ShareActivityLink = 6,
}

export enum NotificationType {
  UserReportedBanned = 1,
  UserReportedThankYou = 2,
  HolidaySale2023Expired = 3,
  GiftMembershipReceivedFromAdmin = 4,
  TranslationHelp = 5,
  UserReportedWarning = 6,
  LiveRoomInvite = 7,
  RoomInviteResponse = 8,
  MissedRoomInvite = 9,
  FriendRequestReceived = 10,
  YouAreNowFriendsWith = 11,
  GiftMembershipReceivedFromUser = 12,
  GiftMembershipWasSent = 13,
  GiftURLCreated = 14,
  NewUserJoinedFromReferral = 15,
  ReferralRewardItemUnlocked = 16,
  YouAreBanned = 17,
  FreeAvatarUnlocked = 18,
  PushReferrersToInviteMoreFriends = 19,
  GeneralAnnouncement = 20,
}

export enum RankTier {
  Grandmaster = 0,
  Master = 1,
  Diamond = 2,
  Platinum = 3,
  Gold = 4,
  Silver = 5,
  Bronze = 6,
  None = 7,
}

export enum RankDivision {
  None = 0,
  I = 1,
  II = 2,
  III = 3,
  IV = 4,
  V = 5,
}

export enum RankStatus {
  Placement = 0,
  Ranked = 1,
  RankedLocked = 2,
}

export enum ProfileTab {
  Overview = 0,
  Ranked = 1,
  History = 2,
  Items = 3,
}

export enum PlayerOptionsAction {
  Report = 0,
  Mute = 1,
  Profile = 2,
  AddFriend = 3,
  BlockTrades = 4,
  Gift = 5,
}

export enum RoomWarningType {
  StartGameVPExceededRecommendedLimit = 0,
  ReadyUpVPExceededRecommendedLimit = 1,
}

export enum ToastType {
  Information = 0,
  Success = 1,
  Warning = 2,
  Error = 3,
  SocketError = 4,
  Reconnect = 5,
}

export enum MatchmakingCategory {
  Bots = 0,
  Casual = 1,
  Ranked = 2,
}

export enum SettingsTab {
  General = 0,
  Volume = 1,
}

export enum AnalyticsPage {
  Leaderboard = 0,
  Lobby = 1,
  Homepage = 2,
  Store = 3,
  Profile = 4,
  Game = 5,
}

export enum LogSeverity {
  JL1 = 0,
  JL2 = 1,
  JL3 = 2,
  JL4 = 3,
  JL5 = 4,
}

export enum MembershipType {
  PlusMonthly = 0,
  PremiumMonthly = 1,
  EliteMonthly = 2,
  PlusYearly = 3,
  PremiumYearly = 4,
  EliteYearly = 5,
  Holiday2023AllAccessPass = 6,
}

export enum GiftMembershipType {
  Holiday2023AllAccessPass = 0,
  GiftPlusMonthly = 1,
  GiftPremiumMonthly = 2,
  GiftEliteMonthly = 3,
  GiftPlusYearly = 4,
  GiftPremiumYearly = 5,
  GiftEliteYearly = 6,
}

export enum ExpansionType {
  Seafarers4P = 0,
  CitiesAndKnights4P = 1,
  TradersAndBarbarians = 2,
  ExplorersAndPirates = 3,
  Classic56P = 4,
  Classic78P = 5,
  Seafarers56P = 6,
  CitiesAndKnights56P = 7,
  CitiesAndKnightsSeafarers4P = 8,
  CitiesAndKnightsSeafarers56P = 9,
}

export enum StoreItemCategory {
  Expansion = 1,
  Map = 2,
  Avatar = 3,
}

export enum StoreMapItemType {
  Earth = 0,
  USA = 1,
  UK = 2,
  Diamond = 3,
  Gear = 4,
  Lakes = 5,
  Pond = 6,
  Twirl = 7,
  Classic4PRandom = 8,
  ShuffleBoard = 9,
  BlackForest = 10,
  Volcano = 11,
  GoldRush = 12,
}

export enum StoreAvatarItemType {
  FounderHat = 0,
  ColonistHat = 1,
  SettlerHat = 2,
  ChristmasHat = 3,
  Player = 4,
  PirateShip = 5,
  MedalGold = 6,
  MedalSilver = 7,
  MedalBronze = 8,
  Elephant = 9,
  Avocado = 10,
  Cactus = 11,
  Crown = 12,
  Swords = 13,
  Helmet = 14,
  Snorkel = 15,
  Scarf = 16,
  Tie = 17,
  Worker = 18,
  Sombrero = 19,
  Farmer = 20,
  RobberSanta = 21,
  RobberLunar = 22,
  RobberCupid = 23,
  Mummy = 24,
  Gifter = 25,
}

export enum GameType {
  Unknown = 0,
  Tutorial = 1,
  BotGame = 2,
  CreatedRoomGame = 3,
  MatchmakingGame = 5,
  MatchmakingGameRanked = 6,
  BeginnerMode = 7,
  CreatedTournamentRoom = 8,
}

export enum GameModeId {
  Classic4P = 0,
  TutorialClassic4P = 1,
  Classic56P = 2,
  Classic78P = 3,
  Seafarers4P = 4,
  Seafarers56P = 5,
  CitiesAndKnights4P = 6,
  CitiesAndKnights56P = 7,
  CitiesAndKnightsSeafarers4P = 8,
  CitiesAndKnightsSeafarers56P = 9,
  ServerStressTestClassic4P = 10,
  BeginnerModeClassic4P = 11,
  ColonistRush4P = 12,
}

export enum MapId {
  Classic4P = 0,
  TutorialClassic4P = 1,
  Classic4PRandom = 2,
  Classic56P = 3,
  Classic78P = 4,
  SS1HeadingForNewShores3P = 5,
  SS1HeadingForNewShores4P = 6,
  SS1HeadingForNewShores56P = 7,
  TutorialSS1HeadingForNewShores4P = 8,
  SS2FourIslands3P = 9,
  SS2FourIslands4P = 10,
  SS2SixIslands56P = 11,
  TutorialSS2FourIslands4P = 12,
  SS3FogIslands3P = 13,
  SS3FogIslands4P = 14,
  SS3FogIslands56P = 15,
  TutorialSS3FogIsland4P = 16,
  SS4ThroughTheDesert3P = 17,
  SS4ThroughTheDesert4P = 18,
  SS4ThroughTheDesert56P = 19,
  TutorialSS4ThroughTheDesert4P = 20,
  KingOfTheHill = 21,
  Earth = 22,
  EarthSeafarers = 23,
  USA = 24,
  UK = 25,
  UKSeafarers = 26,
  Diamond = 27,
  Gear = 28,
  Lakes = 29,
  Pond = 30,
  Twirl = 31,
  ShuffleBoard = 32,
  BlackForest = 33,
  Volcano = 34,
  Circle = 35,
  Kite = 36,
  Romania = 37,
  MiniBase = 38,
  Monopoly = 39,
  MountainOfRiches = 40,
  Doggo = 41,
  Duel = 42,
  TradeIslands = 43,
  TradeIslandsSeafarers = 44,
  Vietnam = 45,
  TurningTidesSeafarers = 46,
  TurningTidesClassic = 47,
  TwoIsles = 48,
  JellyFish = 49,
  GoldRush = 50,
  Istanbul = 51,
  IstanbulSeafarers = 52,
  Europe = 53,
  EuropeSeafarers = 54,
  Stripes = 55,
  MonopolyIslands = 56,
  MonopolyIslandsSeafarers = 57,
  CampaignLevel1 = 58,
  CampaignLevel2 = 59,
  CampaignRoadRace = 60,
  CampaignRoadRace2 = 61,
}

export enum TurnTimerType {
  Base30s = 0,
  Base60s = 1,
  Base120s = 2,
  Base240s = 3,
  Base12000s = 4,
  Rush5s = 5,
  Rush8s = 6,
  Rush10s = 7,
  Rush15s = 8,
  Rush20s = 9,
}

export enum QueueVisibility {
  Inactive = 0,
  HiddenUnranked1v1 = 1,
  HiddenUnranked4PClassic = 2,
  VisibleRanked1v1 = 3,
  VisibleRanked4PClassic = 4,
  VisibleRankedCitiesAndKnights4P = 5,
  HiddenUnrankedShuffle = 6,
}

export enum PlayerCountMode {
  Players4 = 0,
  Players56 = 1,
  Players78 = 2,
}

export enum SeafarersScenarioId {
  None = 0,
  SS1HeadingForNewShores = 1,
  SS2TheFourIslands = 2,
  SS3TheFogIslands = 3,
  SS4ThroughTheDesert = 4,
}

export enum DiceDistributionType {
  Random = 0,
  Balanced = 1,
  StressTestSequence = 2,
  PredefinedDiceSequenceDeleted = 3,
}

export enum AnimationSpeed {
  Fast = 0,
  Normal = 1,
  Slow = 2,
}

export enum UserRole {
  Administrator = 0,
  User = 1,
  Manager = 4,
  Moderator = 5,
}

// Profile icon ids used by userState/icon (subset of shared.c6e... module 78311 i.am).
export enum UserIcon {
  Admin = 9,
  Moderator = 10,
  User = 11,
  Guest = 12,
  Players = 14,
}

export enum PlatformType {
  Unknown = 0,
  Web = 1,
  Discord = 2,
  AppleWeb = 3,
  AppleApp = 4,
  AndroidWeb = 5,
  AndroidApp = 6,
  MobileUnknown = 7,
  DiscordMobile = 8,
}
