import store from "../../../../shared/store";
import { BuildingId, GOOD_IDS, GoodId, PlantationId, RoleId } from "../utils/rules";

type PhaseKey =
  | "role"
  | "settler"
  | "mayor"
  | "builder"
  | "craftsman_bonus"
  | "trader"
  | "captain"
  | "storage"
  | "game_over";

export const THEME_KEYS = [
  "puerto_rico",
  "corpo_rico",
  "porko_rico",
  "puerto_burrito",
  "puerto_disco",
  "puerto_weedo",
  "dowdle_rico",
  "gymbro_rico",
  "puerto_rifto",
  "puerto_sicko",
  "puerto_yugioh",
  "puerto_rato",
  "los_santos_rico",
] as const;

export type PuertoRicoThemeKey = (typeof THEME_KEYS)[number];

export const DEFAULT_THEME_KEY: PuertoRicoThemeKey = "puerto_rico";

export const THEME_OPTIONS: { key: PuertoRicoThemeKey; label: string }[] = [
  { key: "puerto_rico", label: "Puerto Rico" },
  { key: "corpo_rico", label: "Corpo Rico" },
  { key: "porko_rico", label: "Porko Rico" },
  { key: "puerto_burrito", label: "Puerto Burrito" },
  { key: "puerto_disco", label: "Puerto Disco" },
  { key: "puerto_weedo", label: "Puerto Weedo" },
  { key: "dowdle_rico", label: "Dowdle, Rico" },
  { key: "gymbro_rico", label: "GymBro Rico" },
  { key: "puerto_rifto", label: "Puerto Rifto" },
  { key: "puerto_sicko", label: "Puerto Sicko" },
  { key: "puerto_yugioh", label: "Puerto Yugioh" },
  { key: "puerto_rato", label: "Puerto Rato" },
  { key: "los_santos_rico", label: "Los Santos Rico" },
];

const colors = {
  corn: "#f3d66b",
  indigo: "#6e91c8",
  sugar: "#f7f4e6",
  tobacco: "#c18b5a",
  coffee: "#775042",
  quarry: "#b8babd",
  violet: "#d9c3ea",
  large: "#c9b48d",
} as Record<GoodId | "quarry" | "violet" | "large", string>;

type Labels = {
  board: string;
  plantations: string;
  deck: string;
  discard: string;
  quarries: string;
  cargoShips: string;
  tradingHouse: string;
  colonistShip: string;
  goodsSupply: string;
  empty: string;
  open: string;
  goods: string;
  noGoods: string;
  island: string;
  city: string;
  sanJuan: string;
  governor: string;
  doubloons: string;
  roles: string;
  buildings: string;
  cost: string;
  supply: string;
  size: string;
  quarry: string;
  quarriesPlural: string;
  max: string;
  controls: string;
  undo: string;
  home: string;
  rules: string;
  lobby: string;
  log: string;
  leave: string;
  round: string;
  finalScoring: string;
  shipped: string;
  buildingScore: string;
  bonus: string;
  tie: string;
  vp: string;
};

type Actions = {
  chooseRole: string;
  choosingRole: (playerName: string | undefined) => string;
  haciendaTile: string;
  mayorHelp: string;
  buildPrompt: string;
  storagePrompt: string;
  take: string;
  sell: string;
  ship: string;
  onShip: string;
  wharf: string;
  discard: string;
};

type Messages = {
  changedTheme: (themeName: string) => string;
  choseRole: (playerName: string, roleName: string) => string;
  prospected: (playerName: string) => string;
  usedHacienda: (playerName: string, goodName: string) => string;
  settled: (playerName: string, plantationName: string) => string;
  settledQuarry: (playerName: string) => string;
  passed: (playerName: string) => string;
  recalledColonists: (playerName: string) => string;
  placedColonist: (playerName: string) => string;
  movedColonistToSanJuan: (playerName: string) => string;
  finishedColonists: (playerName: string) => string;
  built: (playerName: string, buildingName: string) => string;
  tookExtraGood: (playerName: string, goodName: string) => string;
  skippedExtraGood: (playerName: string) => string;
  producedGoods: () => string;
  sold: (playerName: string, goodName: string) => string;
  shipped: (playerName: string, amount: number, goodName: string) => string;
  usedWharf: (playerName: string, amount: number, goodName: string) => string;
  discarded: (playerName: string, goodName: string) => string;
  stored: (playerName: string) => string;
  phaseFinished: (phaseName: string) => string;
};

type ThemeText = {
  gameName: string;
  rulesUrl: string;
  phase: Record<PhaseKey, string>;
  roles: Record<RoleId, string>;
  roleDescriptions: Record<RoleId, string>;
  roleRewards: Record<RoleId, string>;
  goods: Record<GoodId, string>;
  plantations: Record<PlantationId, string>;
  colors: typeof colors;
  buildings: Record<BuildingId, string>;
  buildingDescriptions: Record<BuildingId, string>;
  disabledPower: string;
  controls: {
    newGame: string;
    pass: string;
    finishPlacement: string;
    clearColonists: string;
    skipBonus: string;
    finishStorage: string;
  };
  labels: Labels;
  actions: Actions;
  messages: Messages;
};

type ThemeOverrides = Partial<Omit<ThemeText, "phase" | "roles" | "roleDescriptions" | "roleRewards" | "goods" | "plantations" | "colors" | "buildings" | "buildingDescriptions" | "controls" | "labels" | "actions" | "messages">> & {
  phase?: Partial<Record<PhaseKey, string>>;
  roles?: Partial<Record<RoleId, string>>;
  roleDescriptions?: Partial<Record<RoleId, string>>;
  roleRewards?: Partial<Record<RoleId, string>>;
  goods?: Partial<Record<GoodId, string>>;
  plantations?: Partial<Record<PlantationId, string>>;
  buildings?: Partial<Record<BuildingId, string>>;
  buildingDescriptions?: Partial<Record<BuildingId, string>>;
  controls?: Partial<ThemeText["controls"]>;
  labels?: Partial<Labels>;
  actions?: Partial<Actions>;
  messages?: Partial<Messages>;
};

const puertoRico: ThemeText = {
  gameName: "Puerto Rico",
  rulesUrl: "https://www.riograndegames.com/wp-content/uploads/2013/02/Puerto-Rico-Rules.pdf",
  phase: {
    role: "Role choice",
    settler: "Settler",
    mayor: "Mayor",
    builder: "Builder",
    craftsman_bonus: "Craftsman bonus",
    trader: "Trader",
    captain: "Captain",
    storage: "Storage",
    game_over: "Game over",
  },
  roles: {
    settler: "Settler",
    mayor: "Mayor",
    builder: "Builder",
    craftsman: "Craftsman",
    trader: "Trader",
    captain: "Captain",
    prospector_1: "Prospector",
    prospector_2: "Prospector",
  } as Record<RoleId, string>,
  roleDescriptions: {
    settler: "Everyone chooses an island tile.",
    mayor: "Everyone places colonists.",
    builder: "Everyone may build one building.",
    craftsman: "Everyone produces goods.",
    trader: "Everyone may sell one good.",
    captain: "Everyone ships goods for VP.",
    prospector_1: "No shared action.",
    prospector_2: "No shared action.",
  } as Record<RoleId, string>,
  roleRewards: {
    settler: "Chooser may take a quarry.",
    mayor: "Chooser takes 1 colonist first.",
    builder: "Chooser pays 1 less.",
    craftsman: "Chooser may take 1 extra good.",
    trader: "Chooser earns +1 doubloon.",
    captain: "Chooser earns +1 VP once.",
    prospector_1: "Chooser takes 1 doubloon.",
    prospector_2: "Chooser takes 1 doubloon.",
  } as Record<RoleId, string>,
  goods: {
    corn: "Corn",
    indigo: "Indigo",
    sugar: "Sugar",
    tobacco: "Tobacco",
    coffee: "Coffee",
  } as Record<GoodId, string>,
  plantations: {
    corn: "Corn",
    indigo: "Indigo",
    sugar: "Sugar",
    tobacco: "Tobacco",
    coffee: "Coffee",
    quarry: "Quarry",
  } as Record<PlantationId, string>,
  colors,
  buildings: {
    small_indigo_plant: "Small Indigo Plant",
    small_sugar_mill: "Small Sugar Mill",
    indigo_plant: "Indigo Plant",
    sugar_mill: "Sugar Mill",
    tobacco_storage: "Tobacco Storage",
    coffee_roaster: "Coffee Roaster",
    small_market: "Small Market",
    hacienda: "Hacienda",
    construction_hut: "Construction Hut",
    small_warehouse: "Small Warehouse",
    hospice: "Hospice",
    office: "Office",
    large_market: "Large Market",
    large_warehouse: "Large Warehouse",
    factory: "Factory",
    university: "University",
    harbor: "Harbor",
    wharf: "Wharf",
    guild_hall: "Guild Hall",
    residence: "Residence",
    fortress: "Fortress",
    customs_house: "Customs House",
    city_hall: "City Hall",
  } as Record<BuildingId, string>,
  buildingDescriptions: {
    small_indigo_plant: "Produces up to 1 indigo with occupied indigo plantations.",
    small_sugar_mill: "Produces up to 1 sugar with occupied sugar plantations.",
    indigo_plant: "Produces up to 3 indigo with occupied indigo plantations.",
    sugar_mill: "Produces up to 3 sugar with occupied sugar plantations.",
    tobacco_storage: "Produces up to 3 tobacco with occupied tobacco plantations.",
    coffee_roaster: "Produces up to 2 coffee with occupied coffee plantations.",
    small_market: "+1 doubloon when selling in the trader phase.",
    hacienda: "May take one face-down plantation before your settler action.",
    construction_hut: "May take a quarry instead of a plantation in the settler phase.",
    small_warehouse: "Stores all barrels of 1 good kind after captain.",
    hospice: "Adds a colonist to a settled plantation or quarry.",
    office: "May sell a good already in the trading house.",
    large_market: "+2 doubloons when selling in the trader phase.",
    large_warehouse: "Stores all barrels of 2 good kinds after captain.",
    factory: "Earns doubloons for producing multiple good kinds.",
    university: "Adds a colonist to a newly built building.",
    harbor: "+1 VP each time you load goods in captain.",
    wharf: "Once per captain phase, ship all goods of one kind to supply.",
    guild_hall: "Game end: +1 VP per small production building, +2 per large.",
    residence: "Game end: +4 to +7 VP for filled island spaces.",
    fortress: "Game end: +1 VP for every 3 colonists.",
    customs_house: "Game end: +1 VP for every 4 shipped VP.",
    city_hall: "Game end: +1 VP for each violet building, including itself.",
  } as Record<BuildingId, string>,
  disabledPower: "Power disabled in core v1",
  controls: {
    newGame: "New Game",
    pass: "Pass",
    finishPlacement: "Finish placement",
    clearColonists: "Clear colonists",
    skipBonus: "Skip bonus",
    finishStorage: "Finish storage",
  },
  labels: {
    board: "Board",
    plantations: "Plantations",
    deck: "Deck",
    discard: "Discard",
    quarries: "Quarries",
    cargoShips: "Cargo ships",
    tradingHouse: "Trading house",
    colonistShip: "Colonist ship",
    goodsSupply: "Goods supply",
    empty: "Empty",
    open: "Open",
    goods: "Goods",
    noGoods: "No goods",
    island: "Island",
    city: "City",
    sanJuan: "San Juan",
    governor: "Governor",
    doubloons: "doubloons",
    roles: "Roles",
    buildings: "Buildings",
    cost: "Cost",
    supply: "Supply",
    size: "Size",
    quarry: "quarry",
    quarriesPlural: "quarries",
    max: "max",
    controls: "Controls",
    undo: "Undo",
    home: "Home",
    rules: "Rules",
    lobby: "Lobby",
    log: "Log",
    leave: "Leave",
    round: "Round",
    finalScoring: "Final scoring",
    shipped: "shipped",
    buildingScore: "buildings",
    bonus: "bonus",
    tie: "tie",
    vp: "VP",
  },
  actions: {
    chooseRole: "Choose a role.",
    choosingRole: (playerName) => `${playerName} is choosing a role.`,
    haciendaTile: "Hacienda tile",
    mayorHelp: "Click worker dots on your island and city to place colonists.",
    buildPrompt: "Build from the market below or pass.",
    storagePrompt: "Discard until your remaining goods fit your warehouse storage.",
    take: "Take",
    sell: "Sell",
    ship: "Ship",
    onShip: "on ship",
    wharf: "Wharf",
    discard: "Discard",
  },
  messages: {
    changedTheme: (themeName) => `changed theme to ${themeName}`,
    choseRole: (playerName, roleName) => `${playerName} chose ${roleName}`,
    prospected: (playerName) => `${playerName} prospected`,
    usedHacienda: (playerName, goodName) => `${playerName} used hacienda for ${goodName}`,
    settled: (playerName, plantationName) => `${playerName} settled ${plantationName}`,
    settledQuarry: (playerName) => `${playerName} settled a quarry`,
    passed: (playerName) => `${playerName} passed`,
    recalledColonists: (playerName) => `${playerName} recalled colonists`,
    placedColonist: (playerName) => `${playerName} placed a colonist`,
    movedColonistToSanJuan: (playerName) => `${playerName} moved a colonist to San Juan`,
    finishedColonists: (playerName) => `${playerName} finished placing colonists`,
    built: (playerName, buildingName) => `${playerName} built ${buildingName}`,
    tookExtraGood: (playerName, goodName) => `${playerName} took an extra ${goodName}`,
    skippedExtraGood: (playerName) => `${playerName} skipped the extra good`,
    producedGoods: () => "produced goods",
    sold: (playerName, goodName) => `${playerName} sold ${goodName}`,
    shipped: (playerName, amount, goodName) => `${playerName} shipped ${amount} ${goodName}`,
    usedWharf: (playerName, amount, goodName) => `${playerName} used wharf for ${amount} ${goodName}`,
    discarded: (playerName, goodName) => `${playerName} discarded ${goodName}`,
    stored: (playerName) => `${playerName} stored goods`,
    phaseFinished: (phaseName) => `${phaseName} finished`,
  },
};

function themed(overrides: ThemeOverrides): ThemeText {
  return {
    ...puertoRico,
    ...overrides,
    phase: { ...puertoRico.phase, ...overrides.phase },
    roles: { ...puertoRico.roles, ...overrides.roles },
    roleDescriptions: { ...puertoRico.roleDescriptions, ...overrides.roleDescriptions },
    roleRewards: { ...puertoRico.roleRewards, ...overrides.roleRewards },
    goods: { ...puertoRico.goods, ...overrides.goods },
    plantations: { ...puertoRico.plantations, ...overrides.plantations },
    colors,
    buildings: { ...puertoRico.buildings, ...overrides.buildings },
    buildingDescriptions: { ...puertoRico.buildingDescriptions, ...overrides.buildingDescriptions },
    controls: { ...puertoRico.controls, ...overrides.controls },
    labels: { ...puertoRico.labels, ...overrides.labels },
    actions: { ...puertoRico.actions, ...overrides.actions },
    messages: { ...puertoRico.messages, ...overrides.messages },
  };
}

function buildingCopy(words: {
  indigo: string;
  sugar: string;
  tobacco: string;
  coffee: string;
  indigoSource: string;
  sugarSource: string;
  tobaccoSource: string;
  coffeeSource: string;
  money: string;
  settler: string;
  quarry: string;
  goods: string;
  captain: string;
  staff: string;
  market: string;
  building: string;
  harbor: string;
  wharf: string;
  smallProduction: string;
  largeProduction: string;
  island: string;
  shipped: string;
  civic: string;
}): Record<BuildingId, string> {
  return {
    small_indigo_plant: `Produces up to 1 ${words.indigo} with occupied ${words.indigoSource}.`,
    small_sugar_mill: `Produces up to 1 ${words.sugar} with occupied ${words.sugarSource}.`,
    indigo_plant: `Produces up to 3 ${words.indigo} with occupied ${words.indigoSource}.`,
    sugar_mill: `Produces up to 3 ${words.sugar} with occupied ${words.sugarSource}.`,
    tobacco_storage: `Produces up to 3 ${words.tobacco} with occupied ${words.tobaccoSource}.`,
    coffee_roaster: `Produces up to 2 ${words.coffee} with occupied ${words.coffeeSource}.`,
    small_market: `+1 ${words.money} when selling in the ${words.market} phase.`,
    hacienda: `May take one hidden ${words.island} before your ${words.settler} action.`,
    construction_hut: `May take a ${words.quarry} instead of a ${words.island} in ${words.settler}.`,
    small_warehouse: `Stores all units of 1 ${words.goods} kind after ${words.captain}.`,
    hospice: `Adds ${words.staff} to a settled ${words.island} or ${words.quarry}.`,
    office: `May sell ${words.goods} already in the trading house.`,
    large_market: `+2 ${words.money} when selling in the ${words.market} phase.`,
    large_warehouse: `Stores all units of 2 ${words.goods} kinds after ${words.captain}.`,
    factory: `Earns ${words.money} for producing multiple ${words.goods} kinds.`,
    university: `Adds ${words.staff} to a newly built ${words.building}.`,
    harbor: `+1 VP each time you load ${words.goods} in ${words.harbor}.`,
    wharf: `Once per ${words.captain}, ship all ${words.goods} of one kind by ${words.wharf}.`,
    guild_hall: `End: +1 VP per ${words.smallProduction}, +2 per ${words.largeProduction}.`,
    residence: `End: +4 to +7 VP for filled ${words.island} spaces.`,
    fortress: `End: +1 VP for every 3 ${words.staff}.`,
    customs_house: `End: +1 VP for every 4 ${words.shipped} VP.`,
    city_hall: `End: +1 VP for each ${words.civic} building, including itself.`,
  };
}

export const THEMES: Record<PuertoRicoThemeKey, ThemeText> = {
  puerto_rico: puertoRico,
  corpo_rico: themed({
    gameName: "Corpo Rico",
    phase: {
      role: "Strategy pick",
      settler: "Expansion",
      mayor: "Staffing",
      builder: "Buildout",
      craftsman_bonus: "Sprint bonus",
      trader: "Sales",
      captain: "Deploy",
      storage: "Inventory",
      game_over: "Closeout",
    },
    roles: {
      settler: "Internship",
      mayor: "Career Fair",
      builder: "Offsite",
      craftsman: "Sprint",
      trader: "Sales Lead",
      captain: "Deploy",
      prospector_1: "Investor",
      prospector_2: "Investor",
    },
    roleDescriptions: {
      settler: "Everyone opens a branch site.",
      mayor: "Everyone assigns staff.",
      builder: "Everyone may launch one office.",
      craftsman: "Everyone lands pharma.",
      trader: "Everyone may close one sale.",
      captain: "Everyone deploys pharma for VP.",
      prospector_1: "No shared action.",
      prospector_2: "No shared action.",
    },
    roleRewards: {
      settler: "Chooser may take data center.",
      mayor: "Chooser hires 1 staff first.",
      builder: "Chooser pays 1 less.",
      craftsman: "Chooser may take 1 extra dose.",
      trader: "Chooser earns +1 stock.",
      captain: "Chooser earns +1 VP once.",
      prospector_1: "Chooser takes 1 stock.",
      prospector_2: "Chooser takes 1 stock.",
    },
    goods: { corn: "Ketamine", indigo: "Adderall", sugar: "Cocaine", tobacco: "Ozempic", coffee: "Caffeine" },
    plantations: {
      corn: "Ketamine",
      indigo: "Adderall",
      sugar: "Cocaine",
      tobacco: "Ozempic",
      coffee: "Caffeine",
      quarry: "Data Center",
    },
    buildings: {
      small_indigo_plant: "Small Adderall Desk",
      small_sugar_mill: "Small Cocaine Desk",
      indigo_plant: "Adderall Department",
      sugar_mill: "Cocaine Department",
      tobacco_storage: "Ozempic Vault",
      coffee_roaster: "Caffeine Lounge",
      small_market: "Small Sales Desk",
      hacienda: "Satellite Office",
      construction_hut: "Procurement Desk",
      small_warehouse: "Small Archive",
      hospice: "HR Clinic",
      office: "Legal Office",
      large_market: "Large Sales Desk",
      large_warehouse: "Large Archive",
      factory: "Sprint Floor",
      university: "Training Campus",
      harbor: "Shipping Desk",
      wharf: "Private Courier",
      guild_hall: "Trade Council",
      residence: "Executive Suite",
      fortress: "Security Office",
      customs_house: "Audit Office",
      city_hall: "Board Room",
    },
    buildingDescriptions: {
      small_indigo_plant: "Produces up to 1 Adderall with staffed Adderall sites.",
      small_sugar_mill: "Produces up to 1 Cocaine with staffed Cocaine sites.",
      indigo_plant: "Produces up to 3 Adderall with staffed Adderall sites.",
      sugar_mill: "Produces up to 3 Cocaine with staffed Cocaine sites.",
      tobacco_storage: "Produces up to 3 Ozempic with staffed Ozempic sites.",
      coffee_roaster: "Produces up to 2 Caffeine with staffed Caffeine sites.",
      small_market: "+1 stock when closing in sales.",
      hacienda: "May take one hidden branch before expansion.",
      construction_hut: "May take a data center instead of a branch.",
      small_warehouse: "Stores all units of 1 pharma kind.",
      hospice: "Adds staff to a new branch or data center.",
      office: "May sell pharma already in the meeting rooms.",
      large_market: "+2 stock when closing in sales.",
      large_warehouse: "Stores all units of 2 pharma kinds.",
      factory: "Earns stock for producing multiple pharma kinds.",
      university: "Adds staff to a newly launched office.",
      harbor: "+1 VP each time you deploy pharma.",
      wharf: "Once per deploy, ship all of one pharma kind.",
      guild_hall: "Closeout: +1 VP per small production office, +2 per large.",
      residence: "Closeout: +4 to +7 VP for filled branch slots.",
      fortress: "Closeout: +1 VP for every 3 staff.",
      customs_house: "Closeout: +1 VP for every 4 shipped VP.",
      city_hall: "Closeout: +1 VP for each corporate office.",
    },
    disabledPower: "Power pending in core v1",
    labels: {
      board: "Dashboard",
      plantations: "Branches",
      deck: "Pipeline",
      discard: "Archive",
      quarries: "Data centers",
      cargoShips: "Backlog",
      tradingHouse: "Meeting rooms",
      colonistShip: "Hiring pool",
      goodsSupply: "Pharma supply",
      empty: "Open",
      open: "Open",
      goods: "Pharma",
      noGoods: "No pharma",
      island: "Network",
      city: "Campus",
      sanJuan: "Bench",
      governor: "Chair",
      doubloons: "stock",
      roles: "Functions",
      buildings: "Offices",
      quarry: "data center",
      quarriesPlural: "data centers",
      finalScoring: "Final audit",
      shipped: "deployed",
      buildingScore: "offices",
    },
    actions: {
      chooseRole: "Choose a function.",
      choosingRole: (playerName) => `${playerName} is choosing a function.`,
      haciendaTile: "Satellite branch",
      mayorHelp: "Click staff dots on your network and campus to assign workers.",
      buildPrompt: "Build from the office market below or pass.",
      storagePrompt: "Discard until remaining pharma fits your archive capacity.",
      take: "Take",
      sell: "Sell",
      ship: "Deploy",
      onShip: "on backlog",
      wharf: "Courier",
      discard: "Discard",
    },
    messages: {
      changedTheme: (themeName) => `changed brand to ${themeName}`,
      choseRole: (playerName, roleName) => `${playerName} picked ${roleName}`,
      prospected: (playerName) => `${playerName} secured funding`,
      usedHacienda: (playerName, goodName) => `${playerName} opened satellite for ${goodName}`,
      settled: (playerName, plantationName) => `${playerName} opened ${plantationName}`,
      settledQuarry: (playerName) => `${playerName} opened a data center`,
      passed: (playerName) => `${playerName} passed`,
      recalledColonists: (playerName) => `${playerName} recalled staff`,
      placedColonist: (playerName) => `${playerName} assigned staff`,
      movedColonistToSanJuan: (playerName) => `${playerName} moved staff to bench`,
      finishedColonists: (playerName) => `${playerName} finished staffing`,
      built: (playerName, buildingName) => `${playerName} launched ${buildingName}`,
      tookExtraGood: (playerName, goodName) => `${playerName} took extra ${goodName}`,
      skippedExtraGood: (playerName) => `${playerName} skipped the extra dose`,
      producedGoods: () => "landed pharma",
      sold: (playerName, goodName) => `${playerName} sold ${goodName}`,
      shipped: (playerName, amount, goodName) => `${playerName} deployed ${amount} ${goodName}`,
      usedWharf: (playerName, amount, goodName) => `${playerName} couriered ${amount} ${goodName}`,
      discarded: (playerName, goodName) => `${playerName} discarded ${goodName}`,
      stored: (playerName) => `${playerName} archived pharma`,
      phaseFinished: (phaseName) => `${phaseName} finished`,
    },
  }),
  porko_rico: themed({
    gameName: "Porko Rico",
    phase: {
      role: "Chore choice",
      settler: "Pasture",
      mayor: "Farmhand",
      builder: "Barn raising",
      craftsman_bonus: "Slop bonus",
      trader: "Market",
      captain: "Hauling",
      storage: "Feed bin",
      game_over: "Fair judging",
    },
    roles: {
      settler: "Pasture Boss",
      mayor: "Farmhand",
      builder: "Barn Raiser",
      craftsman: "Slop Maker",
      trader: "Market Hog",
      captain: "Hauler",
      prospector_1: "Truffle Snout",
      prospector_2: "Truffle Snout",
    },
    roleDescriptions: {
      settler: "Everyone chooses a pasture tile.",
      mayor: "Everyone places farmhands.",
      builder: "Everyone may raise one barn.",
      craftsman: "Everyone makes feed.",
      trader: "Everyone may sell one feed.",
      captain: "Everyone hauls feed for VP.",
      prospector_1: "No shared chore.",
      prospector_2: "No shared chore.",
    },
    roleRewards: {
      settler: "Chooser may take a mud pit.",
      mayor: "Chooser takes 1 farmhand first.",
      builder: "Chooser pays 1 less.",
      craftsman: "Chooser may take 1 extra feed.",
      trader: "Chooser earns +1 coin.",
      captain: "Chooser earns +1 VP once.",
      prospector_1: "Chooser takes 1 coin.",
      prospector_2: "Chooser takes 1 coin.",
    },
    goods: { corn: "Corn", indigo: "Mash", sugar: "Apples", tobacco: "Straw", coffee: "Truffles" },
    plantations: {
      corn: "Corn",
      indigo: "Mash",
      sugar: "Apples",
      tobacco: "Straw",
      coffee: "Truffles",
      quarry: "Mud Pit",
    },
    buildings: {
      small_indigo_plant: "Small Mash Trough",
      small_sugar_mill: "Small Apple Press",
      indigo_plant: "Mash Trough",
      sugar_mill: "Apple Press",
      tobacco_storage: "Straw Loft",
      coffee_roaster: "Truffle Shed",
      small_market: "Small Farm Stand",
      hacienda: "Back Pasture",
      construction_hut: "Mud Hut",
      small_warehouse: "Small Feed Bin",
      hospice: "Vet Stall",
      office: "Fence Office",
      large_market: "Large Farm Stand",
      large_warehouse: "Large Feed Bin",
      factory: "Slop Kitchen",
      university: "Pig School",
      harbor: "Loading Pen",
      wharf: "Private Cart",
      guild_hall: "El Farolito",
      residence: "La Taqueria",
      fortress: "Los Tacos",
      customs_house: "Son Del Norte",
      city_hall: "Taco Bell",
    },
    buildingDescriptions: buildingCopy({
      indigo: "mash",
      sugar: "apples",
      tobacco: "straw",
      coffee: "truffles",
      indigoSource: "mash pastures",
      sugarSource: "apple pastures",
      tobaccoSource: "straw pastures",
      coffeeSource: "truffle pastures",
      money: "coins",
      settler: "pasture",
      quarry: "mud pit",
      goods: "feed",
      captain: "hauling",
      staff: "a farmhand",
      market: "market",
      building: "barn",
      harbor: "hauling",
      wharf: "cart",
      smallProduction: "small feed barn",
      largeProduction: "large",
      island: "pasture",
      shipped: "hauled",
      civic: "barnyard",
    }),
    labels: {
      board: "Farmyard",
      plantations: "Pastures",
      quarries: "Mud pits",
      cargoShips: "Hauling carts",
      tradingHouse: "Market pen",
      colonistShip: "Farmhand cart",
      goodsSupply: "Feed supply",
      empty: "Empty",
      open: "Open",
      goods: "Feed",
      noGoods: "No feed",
      island: "Pasture",
      city: "Barnyard",
      sanJuan: "Pen",
      governor: "Top Hog",
      doubloons: "coins",
      roles: "Chores",
      buildings: "Barns",
      quarry: "mud pit",
      quarriesPlural: "mud pits",
      finalScoring: "Fair judging",
      shipped: "hauled",
      buildingScore: "barns",
    },
    actions: {
      chooseRole: "Choose a chore.",
      choosingRole: (playerName) => `${playerName} is choosing a chore.`,
      haciendaTile: "Back pasture",
      mayorHelp: "Click farmhand dots on your pasture and barnyard to place workers.",
      buildPrompt: "Raise from the barn market below or pass.",
      storagePrompt: "Discard until remaining feed fits your bins.",
      take: "Take",
      sell: "Sell",
      ship: "Haul",
      onShip: "on cart",
      wharf: "Cart",
      discard: "Discard",
    },
    messages: {
      changedTheme: (themeName) => `changed farm sign to ${themeName}`,
      choseRole: (playerName, roleName) => `${playerName} chose ${roleName}`,
      prospected: (playerName) => `${playerName} sniffed truffles`,
      usedHacienda: (playerName, goodName) => `${playerName} used back pasture for ${goodName}`,
      settled: (playerName, plantationName) => `${playerName} fenced ${plantationName}`,
      settledQuarry: (playerName) => `${playerName} claimed a mud pit`,
      passed: (playerName) => `${playerName} passed`,
      recalledColonists: (playerName) => `${playerName} recalled farmhands`,
      placedColonist: (playerName) => `${playerName} placed a farmhand`,
      movedColonistToSanJuan: (playerName) => `${playerName} moved a farmhand to pen`,
      finishedColonists: (playerName) => `${playerName} finished chores`,
      built: (playerName, buildingName) => `${playerName} raised ${buildingName}`,
      tookExtraGood: (playerName, goodName) => `${playerName} took extra ${goodName}`,
      skippedExtraGood: (playerName) => `${playerName} skipped extra feed`,
      producedGoods: () => "made feed",
      sold: (playerName, goodName) => `${playerName} sold ${goodName}`,
      shipped: (playerName, amount, goodName) => `${playerName} hauled ${amount} ${goodName}`,
      usedWharf: (playerName, amount, goodName) => `${playerName} carted ${amount} ${goodName}`,
      discarded: (playerName, goodName) => `${playerName} discarded ${goodName}`,
      stored: (playerName) => `${playerName} stored feed`,
      phaseFinished: (phaseName) => `${phaseName} finished`,
    },
  }),
  puerto_burrito: themed({
    gameName: "Puerto Burrito",
    phase: {
      role: "Station choice",
      settler: "Prep",
      mayor: "Staffing",
      builder: "Buildout",
      craftsman_bonus: "Prep bonus",
      trader: "Window",
      captain: "Service",
      storage: "Walk-in",
      game_over: "Last call",
    },
    roles: {
      settler: "Prep Cook",
      mayor: "Shift Lead",
      builder: "Truck Builder",
      craftsman: "Line Cook",
      trader: "Cashier",
      captain: "Runner",
      prospector_1: "Tip Jar",
      prospector_2: "Tip Jar",
    },
    roleDescriptions: {
      settler: "Everyone chooses a prep tray.",
      mayor: "Everyone places crew.",
      builder: "Everyone may install one station.",
      craftsman: "Everyone preps fillings.",
      trader: "Everyone may sell one filling.",
      captain: "Everyone serves orders for VP.",
      prospector_1: "No shared station.",
      prospector_2: "No shared station.",
    },
    roleRewards: {
      settler: "Chooser may take a commissary.",
      mayor: "Chooser takes 1 crew first.",
      builder: "Chooser pays 1 less.",
      craftsman: "Chooser may take 1 extra filling.",
      trader: "Chooser earns +1 tip.",
      captain: "Chooser earns +1 VP once.",
      prospector_1: "Chooser takes 1 tip.",
      prospector_2: "Chooser takes 1 tip.",
    },
    goods: { corn: "Barbacoa", indigo: "Chicken", sugar: "Pork", tobacco: "Chorizo", coffee: "Steak" },
    plantations: {
      corn: "Barbacoa",
      indigo: "Chicken",
      sugar: "Pork",
      tobacco: "Chorizo",
      coffee: "Steak",
      quarry: "Commissary",
    },
    buildings: {
      small_indigo_plant: "Small Chicken Grill",
      small_sugar_mill: "Small Pork Plancha",
      indigo_plant: "Chicken Grill",
      sugar_mill: "Pork Plancha",
      tobacco_storage: "Chorizo Station",
      coffee_roaster: "Steak Grill",
      small_market: "Small Window",
      hacienda: "Secret Supplier",
      construction_hut: "Commissary Pass",
      small_warehouse: "Small Walk-in",
      hospice: "Staff Meal",
      office: "Menu Hack",
      large_market: "Large Window",
      large_warehouse: "Large Walk-in",
      factory: "Prep Line",
      university: "Training Shift",
      harbor: "Pickup Shelf",
      wharf: "Catering Van",
      guild_hall: "Food Court",
      residence: "Dining Patio",
      fortress: "Health Desk",
      customs_house: "Receipt Box",
      city_hall: "Truck HQ",
    },
    buildingDescriptions: buildingCopy({
      indigo: "chicken",
      sugar: "pork",
      tobacco: "chorizo",
      coffee: "steak",
      indigoSource: "chicken trays",
      sugarSource: "pork trays",
      tobaccoSource: "chorizo trays",
      coffeeSource: "steak trays",
      money: "tips",
      settler: "prep",
      quarry: "commissary",
      goods: "filling",
      captain: "service",
      staff: "crew",
      market: "window",
      building: "station",
      harbor: "service",
      wharf: "catering van",
      smallProduction: "small prep station",
      largeProduction: "large",
      island: "prep tray",
      shipped: "served",
      civic: "truck",
    }),
    labels: {
      board: "Service Board",
      plantations: "Prep trays",
      quarries: "Commissaries",
      cargoShips: "Order rails",
      tradingHouse: "Service window",
      colonistShip: "Staff call",
      goodsSupply: "Filling stock",
      empty: "Open",
      open: "Open",
      goods: "Fillings",
      noGoods: "No fillings",
      island: "Prep",
      city: "Truck",
      sanJuan: "Break",
      governor: "Chef",
      doubloons: "tips",
      roles: "Stations",
      buildings: "Stations",
      quarry: "commissary",
      quarriesPlural: "commissaries",
      finalScoring: "Last call",
      shipped: "served",
      buildingScore: "stations",
    },
    actions: {
      chooseRole: "Choose a station.",
      choosingRole: (playerName) => `${playerName} is choosing a station.`,
      haciendaTile: "Secret prep tray",
      mayorHelp: "Click crew dots on your prep and truck to staff stations.",
      buildPrompt: "Build from the station market below or pass.",
      storagePrompt: "Discard until remaining fillings fit your walk-in.",
      take: "Take",
      sell: "Sell",
      ship: "Serve",
      onShip: "on rail",
      wharf: "Cater",
      discard: "Discard",
    },
    messages: {
      changedTheme: (themeName) => `changed menu to ${themeName}`,
      choseRole: (playerName, roleName) => `${playerName} chose ${roleName}`,
      prospected: (playerName) => `${playerName} emptied the tip jar`,
      usedHacienda: (playerName, goodName) => `${playerName} prepped secret ${goodName}`,
      settled: (playerName, plantationName) => `${playerName} prepped ${plantationName}`,
      settledQuarry: (playerName) => `${playerName} booked a commissary`,
      passed: (playerName) => `${playerName} passed`,
      recalledColonists: (playerName) => `${playerName} recalled crew`,
      placedColonist: (playerName) => `${playerName} staffed a station`,
      movedColonistToSanJuan: (playerName) => `${playerName} sent crew on break`,
      finishedColonists: (playerName) => `${playerName} finished staffing`,
      built: (playerName, buildingName) => `${playerName} installed ${buildingName}`,
      tookExtraGood: (playerName, goodName) => `${playerName} took extra ${goodName}`,
      skippedExtraGood: (playerName) => `${playerName} skipped extra prep`,
      producedGoods: () => "prepped fillings",
      sold: (playerName, goodName) => `${playerName} sold ${goodName}`,
      shipped: (playerName, amount, goodName) => `${playerName} served ${amount} ${goodName}`,
      usedWharf: (playerName, amount, goodName) => `${playerName} catered ${amount} ${goodName}`,
      discarded: (playerName, goodName) => `${playerName} tossed ${goodName}`,
      stored: (playerName) => `${playerName} stocked fillings`,
      phaseFinished: (phaseName) => `${phaseName} finished`,
    },
  }),
  puerto_disco: themed({
    gameName: "Puerto Disco",
    phase: {
      role: "Set choice",
      settler: "Floor",
      mayor: "Crowd",
      builder: "Rigging",
      craftsman_bonus: "Groove bonus",
      trader: "Bar",
      captain: "Encore",
      storage: "Backstage",
      game_over: "Last dance",
    },
    roles: {
      settler: "Floor Manager",
      mayor: "Hype Lead",
      builder: "Light Tech",
      craftsman: "DJ",
      trader: "Bartender",
      captain: "Promoter",
      prospector_1: "VIP Guest",
      prospector_2: "VIP Guest",
    },
    roleDescriptions: {
      settler: "Everyone chooses a dance floor.",
      mayor: "Everyone places dancers.",
      builder: "Everyone may open one room.",
      craftsman: "Everyone tunes instruments.",
      trader: "Everyone may sell one instrument.",
      captain: "Everyone plays instruments for VP.",
      prospector_1: "No shared set.",
      prospector_2: "No shared set.",
    },
    roleRewards: {
      settler: "Chooser may take a mirror ball.",
      mayor: "Chooser takes 1 dancer first.",
      builder: "Chooser pays 1 less.",
      craftsman: "Chooser may tune 1 extra instrument.",
      trader: "Chooser earns +1 cover.",
      captain: "Chooser earns +1 VP once.",
      prospector_1: "Chooser takes 1 cover.",
      prospector_2: "Chooser takes 1 cover.",
    },
    goods: { corn: "Drums", indigo: "Bass", sugar: "Keys", tobacco: "Guitar", coffee: "Vocals" },
    plantations: {
      corn: "Drums",
      indigo: "Bass",
      sugar: "Keys",
      tobacco: "Guitar",
      coffee: "Vocals",
      quarry: "Mirror Ball",
    },
    buildings: {
      small_indigo_plant: "Small Bass Booth",
      small_sugar_mill: "Small Keytar Stand",
      indigo_plant: "Bass Booth",
      sugar_mill: "Keytar Stand",
      tobacco_storage: "Guitar Rack",
      coffee_roaster: "Vocal Booth",
      small_market: "Small Cover Desk",
      hacienda: "Back Door",
      construction_hut: "Mirror Crew",
      small_warehouse: "Small Backstage",
      hospice: "Green Room",
      office: "Guest List",
      large_market: "Large Cover Desk",
      large_warehouse: "Large Backstage",
      factory: "Remix Booth",
      university: "Dance School",
      harbor: "Encore Rail",
      wharf: "VIP Exit",
      guild_hall: "Bee Gees",
      residence: "Chic",
      fortress: "KC Sunshine Band",
      customs_house: "Earth Wind Fire",
      city_hall: "ABBA",
    },
    buildingDescriptions: buildingCopy({
      indigo: "bass",
      sugar: "keys",
      tobacco: "guitar",
      coffee: "vocals",
      indigoSource: "bass floors",
      sugarSource: "keys floors",
      tobaccoSource: "guitar floors",
      coffeeSource: "vocal floors",
      money: "cover",
      settler: "floor",
      quarry: "mirror ball",
      goods: "instrument",
      captain: "encore",
      staff: "a dancer",
      market: "bar",
      building: "room",
      harbor: "encore",
      wharf: "VIP exit",
      smallProduction: "small instrument room",
      largeProduction: "large",
      island: "floor",
      shipped: "played",
      civic: "club",
    }),
    labels: {
      board: "Club Board",
      plantations: "Dance floors",
      quarries: "Mirror balls",
      cargoShips: "Encore rails",
      tradingHouse: "Bar rail",
      colonistShip: "Guest line",
      goodsSupply: "Instrument supply",
      empty: "Open",
      open: "Open",
      goods: "Instruments",
      noGoods: "No instruments",
      island: "Floor",
      city: "Club",
      sanJuan: "Queue",
      governor: "Headliner",
      doubloons: "cover",
      roles: "Sets",
      buildings: "Rooms",
      quarry: "mirror ball",
      quarriesPlural: "mirror balls",
      finalScoring: "Last dance",
      shipped: "played",
      buildingScore: "rooms",
    },
    actions: {
      chooseRole: "Choose a set.",
      choosingRole: (playerName) => `${playerName} is choosing a set.`,
      haciendaTile: "Back-door floor",
      mayorHelp: "Click dancer dots on your floor and club to fill spots.",
      buildPrompt: "Build from the room market below or pass.",
      storagePrompt: "Discard until remaining instruments fit backstage.",
      take: "Take",
      sell: "Sell",
      ship: "Play",
      onShip: "on rail",
      wharf: "VIP",
      discard: "Drop",
    },
    messages: {
      changedTheme: (themeName) => `changed the set to ${themeName}`,
      choseRole: (playerName, roleName) => `${playerName} chose ${roleName}`,
      prospected: (playerName) => `${playerName} hit the VIP list`,
      usedHacienda: (playerName, goodName) => `${playerName} opened back door for ${goodName}`,
      settled: (playerName, plantationName) => `${playerName} lit ${plantationName}`,
      settledQuarry: (playerName) => `${playerName} hung a mirror ball`,
      passed: (playerName) => `${playerName} passed`,
      recalledColonists: (playerName) => `${playerName} cleared dancers`,
      placedColonist: (playerName) => `${playerName} placed a dancer`,
      movedColonistToSanJuan: (playerName) => `${playerName} moved a dancer to queue`,
      finishedColonists: (playerName) => `${playerName} finished the crowd`,
      built: (playerName, buildingName) => `${playerName} opened ${buildingName}`,
      tookExtraGood: (playerName, goodName) => `${playerName} took extra ${goodName}`,
      skippedExtraGood: (playerName) => `${playerName} skipped the extra instrument`,
      producedGoods: () => "tuned instruments",
      sold: (playerName, goodName) => `${playerName} sold ${goodName}`,
      shipped: (playerName, amount, goodName) => `${playerName} played ${amount} ${goodName}`,
      usedWharf: (playerName, amount, goodName) => `${playerName} VIP'd ${amount} ${goodName}`,
      discarded: (playerName, goodName) => `${playerName} dropped ${goodName}`,
      stored: (playerName) => `${playerName} stashed instruments`,
      phaseFinished: (phaseName) => `${phaseName} finished`,
    },
  }),
  puerto_weedo: themed({
    gameName: "Puerto Weedo",
    phase: {
      role: "Strain choice",
      settler: "Garden",
      mayor: "Crew",
      builder: "Buildout",
      craftsman_bonus: "Harvest bonus",
      trader: "Dispensary",
      captain: "Delivery",
      storage: "Curing",
      game_over: "Final weigh-in",
    },
    roles: {
      settler: "Grower",
      mayor: "Crew Lead",
      builder: "Builder",
      craftsman: "Harvester",
      trader: "Budtender",
      captain: "Courier",
      prospector_1: "Investor",
      prospector_2: "Investor",
    },
    roleDescriptions: {
      settler: "Everyone chooses a garden tile.",
      mayor: "Everyone places crew.",
      builder: "Everyone may build one room.",
      craftsman: "Everyone harvests product.",
      trader: "Everyone may sell one product.",
      captain: "Everyone delivers product for VP.",
      prospector_1: "No shared shift.",
      prospector_2: "No shared shift.",
    },
    roleRewards: {
      settler: "Chooser may take a grow light.",
      mayor: "Chooser takes 1 crew first.",
      builder: "Chooser pays 1 less.",
      craftsman: "Chooser may take 1 extra product.",
      trader: "Chooser earns +1 cash.",
      captain: "Chooser earns +1 VP once.",
      prospector_1: "Chooser takes 1 cash.",
      prospector_2: "Chooser takes 1 cash.",
    },
    goods: { corn: "Clones", indigo: "Flower", sugar: "Edibles", tobacco: "Pre-rolls", coffee: "Concentrate" },
    plantations: {
      corn: "Clones",
      indigo: "Flower",
      sugar: "Edibles",
      tobacco: "Pre-rolls",
      coffee: "Concentrate",
      quarry: "Grow Light",
    },
    buildings: {
      small_indigo_plant: "Small Flower Room",
      small_sugar_mill: "Small Edible Kitchen",
      indigo_plant: "Flower Room",
      sugar_mill: "Edible Kitchen",
      tobacco_storage: "Pre-roll Table",
      coffee_roaster: "Extraction Lab",
      small_market: "Small Counter",
      hacienda: "Hidden Plot",
      construction_hut: "Grow Shop",
      small_warehouse: "Small Cure Room",
      hospice: "Clone Nursery",
      office: "Compliance Desk",
      large_market: "Large Counter",
      large_warehouse: "Large Cure Room",
      factory: "Processing Lab",
      university: "Training Grow",
      harbor: "Delivery Desk",
      wharf: "Private Courier",
      guild_hall: "Cheech and Chong",
      residence: "Snoop Dogg",
      fortress: "Willie Nelson",
      customs_house: "Bob Marley",
      city_hall: "Barack Obama",
    },
    buildingDescriptions: buildingCopy({
      indigo: "flower",
      sugar: "edibles",
      tobacco: "pre-rolls",
      coffee: "concentrate",
      indigoSource: "flower gardens",
      sugarSource: "edible gardens",
      tobaccoSource: "pre-roll gardens",
      coffeeSource: "concentrate gardens",
      money: "cash",
      settler: "garden",
      quarry: "grow light",
      goods: "product",
      captain: "delivery",
      staff: "crew",
      market: "dispensary",
      building: "room",
      harbor: "delivery",
      wharf: "courier",
      smallProduction: "small grow room",
      largeProduction: "large",
      island: "garden",
      shipped: "delivered",
      civic: "facility",
    }),
    labels: {
      board: "Grow Board",
      plantations: "Gardens",
      quarries: "Grow lights",
      cargoShips: "Delivery runs",
      tradingHouse: "Dispensary case",
      colonistShip: "Crew van",
      goodsSupply: "Product supply",
      empty: "Open",
      open: "Open",
      goods: "Product",
      noGoods: "No product",
      island: "Garden",
      city: "Facility",
      sanJuan: "Break room",
      governor: "Head Grower",
      doubloons: "cash",
      roles: "Shifts",
      buildings: "Rooms",
      quarry: "grow light",
      quarriesPlural: "grow lights",
      finalScoring: "Final weigh-in",
      shipped: "delivered",
      buildingScore: "rooms",
    },
    actions: {
      chooseRole: "Choose a shift.",
      choosingRole: (playerName) => `${playerName} is choosing a shift.`,
      haciendaTile: "Hidden garden",
      mayorHelp: "Click crew dots on your garden and facility to staff rooms.",
      buildPrompt: "Build from the room market below or pass.",
      storagePrompt: "Discard until remaining product fits your cure rooms.",
      take: "Take",
      sell: "Sell",
      ship: "Deliver",
      onShip: "on run",
      wharf: "Courier",
      discard: "Discard",
    },
    messages: {
      changedTheme: (themeName) => `changed strain board to ${themeName}`,
      choseRole: (playerName, roleName) => `${playerName} chose ${roleName}`,
      prospected: (playerName) => `${playerName} found investors`,
      usedHacienda: (playerName, goodName) => `${playerName} planted hidden ${goodName}`,
      settled: (playerName, plantationName) => `${playerName} planted ${plantationName}`,
      settledQuarry: (playerName) => `${playerName} hung a grow light`,
      passed: (playerName) => `${playerName} passed`,
      recalledColonists: (playerName) => `${playerName} recalled crew`,
      placedColonist: (playerName) => `${playerName} staffed a room`,
      movedColonistToSanJuan: (playerName) => `${playerName} moved crew to break room`,
      finishedColonists: (playerName) => `${playerName} finished staffing`,
      built: (playerName, buildingName) => `${playerName} built ${buildingName}`,
      tookExtraGood: (playerName, goodName) => `${playerName} took extra ${goodName}`,
      skippedExtraGood: (playerName) => `${playerName} skipped extra harvest`,
      producedGoods: () => "harvested product",
      sold: (playerName, goodName) => `${playerName} sold ${goodName}`,
      shipped: (playerName, amount, goodName) => `${playerName} delivered ${amount} ${goodName}`,
      usedWharf: (playerName, amount, goodName) => `${playerName} couriered ${amount} ${goodName}`,
      discarded: (playerName, goodName) => `${playerName} discarded ${goodName}`,
      stored: (playerName) => `${playerName} cured product`,
      phaseFinished: (phaseName) => `${phaseName} finished`,
    },
  }),
  dowdle_rico: themed({
    gameName: "Dowdle, Rico",
    phase: {
      role: "Play call",
      settler: "Recruiting",
      mayor: "Depth chart",
      builder: "Facilities",
      craftsman_bonus: "Drive bonus",
      trader: "Transfer",
      captain: "Game day",
      storage: "Locker room",
      game_over: "Final whistle",
    },
    roles: {
      settler: "Recruiter",
      mayor: "Position Coach",
      builder: "Facilities",
      craftsman: "Offense",
      trader: "Agent",
      captain: "Head Coach",
      prospector_1: "Booster",
      prospector_2: "Booster",
    },
    roleDescriptions: {
      settler: "Everyone chooses a play sheet.",
      mayor: "Everyone places players.",
      builder: "Everyone may build one facility.",
      craftsman: "Everyone generates stats.",
      trader: "Everyone may trade one stat.",
      captain: "Everyone scores stats for VP.",
      prospector_1: "No shared play.",
      prospector_2: "No shared play.",
    },
    roleRewards: {
      settler: "Chooser may take a weight room.",
      mayor: "Chooser takes 1 player first.",
      builder: "Chooser pays 1 less.",
      craftsman: "Chooser may take 1 extra stat.",
      trader: "Chooser earns +1 booster.",
      captain: "Chooser earns +1 VP once.",
      prospector_1: "Chooser takes 1 booster.",
      prospector_2: "Chooser takes 1 booster.",
    },
    goods: { corn: "Yards", indigo: "Blocks", sugar: "Routes", tobacco: "Tackles", coffee: "Touchdowns" },
    plantations: {
      corn: "Yards",
      indigo: "Blocks",
      sugar: "Routes",
      tobacco: "Tackles",
      coffee: "Touchdowns",
      quarry: "Weight Room",
    },
    buildings: {
      small_indigo_plant: "Small Blocking Sled",
      small_sugar_mill: "Small Route Tree",
      indigo_plant: "Blocking Sled",
      sugar_mill: "Route Tree",
      tobacco_storage: "Tackle Drill",
      coffee_roaster: "Red Zone Room",
      small_market: "Small Booster Table",
      hacienda: "Recruiting Trip",
      construction_hut: "Weight Plan",
      small_warehouse: "Small Locker",
      hospice: "Training Table",
      office: "Film Room",
      large_market: "Large Booster Table",
      large_warehouse: "Large Locker",
      factory: "Practice Field",
      university: "Playbook Class",
      harbor: "End Zone",
      wharf: "Hail Mary",
      guild_hall: "Joseph Manjack IV",
      residence: "Squirrel White",
      fortress: "Ka'morreun Pimpton",
      customs_house: "Thunder Justice Keck",
      city_hall: "General Booty",
    },
    buildingDescriptions: buildingCopy({
      indigo: "blocks",
      sugar: "routes",
      tobacco: "tackles",
      coffee: "touchdowns",
      indigoSource: "blocking sheets",
      sugarSource: "route sheets",
      tobaccoSource: "tackle sheets",
      coffeeSource: "touchdown sheets",
      money: "boosters",
      settler: "recruiting",
      quarry: "weight room",
      goods: "stat",
      captain: "game day",
      staff: "a player",
      market: "transfer",
      building: "facility",
      harbor: "game day",
      wharf: "Hail Mary",
      smallProduction: "small drill room",
      largeProduction: "large",
      island: "field",
      shipped: "scored",
      civic: "program",
    }),
    labels: {
      board: "Scoreboard",
      plantations: "Play sheets",
      quarries: "Weight rooms",
      cargoShips: "Drives",
      tradingHouse: "Transfer portal",
      colonistShip: "Bench squad",
      goodsSupply: "Stat supply",
      empty: "Open",
      open: "Open",
      goods: "Stats",
      noGoods: "No stats",
      island: "Field",
      city: "Program",
      sanJuan: "Bench",
      governor: "Captain",
      doubloons: "boosters",
      roles: "Play calls",
      buildings: "Facilities",
      quarry: "weight room",
      quarriesPlural: "weight rooms",
      finalScoring: "Final whistle",
      shipped: "scored",
      buildingScore: "facilities",
    },
    actions: {
      chooseRole: "Choose a play.",
      choosingRole: (playerName) => `${playerName} is calling a play.`,
      haciendaTile: "Recruiting trip",
      mayorHelp: "Click player dots on your field and program to set the depth chart.",
      buildPrompt: "Build from the facility market below or pass.",
      storagePrompt: "Discard until remaining stats fit your locker room.",
      take: "Take",
      sell: "Trade",
      ship: "Score",
      onShip: "on drive",
      wharf: "Hail Mary",
      discard: "Cut",
    },
    messages: {
      changedTheme: (themeName) => `changed playbook to ${themeName}`,
      choseRole: (playerName, roleName) => `${playerName} called ${roleName}`,
      prospected: (playerName) => `${playerName} met boosters`,
      usedHacienda: (playerName, goodName) => `${playerName} recruited ${goodName}`,
      settled: (playerName, plantationName) => `${playerName} recruited ${plantationName}`,
      settledQuarry: (playerName) => `${playerName} opened a weight room`,
      passed: (playerName) => `${playerName} punted`,
      recalledColonists: (playerName) => `${playerName} reset the depth chart`,
      placedColonist: (playerName) => `${playerName} slotted a player`,
      movedColonistToSanJuan: (playerName) => `${playerName} moved a player to bench`,
      finishedColonists: (playerName) => `${playerName} set the lineup`,
      built: (playerName, buildingName) => `${playerName} built ${buildingName}`,
      tookExtraGood: (playerName, goodName) => `${playerName} took extra ${goodName}`,
      skippedExtraGood: (playerName) => `${playerName} skipped the extra stat`,
      producedGoods: () => "ran the offense",
      sold: (playerName, goodName) => `${playerName} traded ${goodName}`,
      shipped: (playerName, amount, goodName) => `${playerName} scored ${amount} ${goodName}`,
      usedWharf: (playerName, amount, goodName) => `${playerName} hit ${amount} ${goodName}`,
      discarded: (playerName, goodName) => `${playerName} cut ${goodName}`,
      stored: (playerName) => `${playerName} stored the stats`,
      phaseFinished: (phaseName) => `${phaseName} finished`,
    },
  }),
  gymbro_rico: themed({
    gameName: "GymBro Rico",
    phase: {
      role: "Split choice",
      settler: "Bulk",
      mayor: "Spotting",
      builder: "Equipment",
      craftsman_bonus: "Pump bonus",
      trader: "Pose down",
      captain: "Flex",
      storage: "Locker",
      game_over: "Final flex",
    },
    roles: {
      settler: "New Year Bro",
      mayor: "Spotter",
      builder: "Equipment Guy",
      craftsman: "Pump Chaser",
      trader: "Posing Coach",
      captain: "Influencer",
      prospector_1: "Locker Coin",
      prospector_2: "Locker Coin",
    },
    roleDescriptions: {
      settler: "Everyone chooses a workout tile.",
      mayor: "Everyone places gym bros.",
      builder: "Everyone may install one station.",
      craftsman: "Everyone gets gains.",
      trader: "Everyone may sell one muscle group.",
      captain: "Everyone flexes gains for VP.",
      prospector_1: "No shared lift.",
      prospector_2: "No shared lift.",
    },
    roleRewards: {
      settler: "Chooser may take a squat rack.",
      mayor: "Chooser takes 1 gym bro first.",
      builder: "Chooser pays 1 less.",
      craftsman: "Chooser may train 1 extra muscle.",
      trader: "Chooser earns +1 protein.",
      captain: "Chooser earns +1 VP once.",
      prospector_1: "Chooser takes 1 protein.",
      prospector_2: "Chooser takes 1 protein.",
    },
    goods: { corn: "Legs", indigo: "Back", sugar: "Chest", tobacco: "Shoulders", coffee: "Arms" },
    plantations: {
      corn: "Legs",
      indigo: "Back",
      sugar: "Chest",
      tobacco: "Shoulders",
      coffee: "Arms",
      quarry: "Squat Rack",
    },
    buildings: {
      small_indigo_plant: "Small Back Machine",
      small_sugar_mill: "Small Chest Press",
      indigo_plant: "Back Machine",
      sugar_mill: "Chest Press",
      tobacco_storage: "Shoulder Rack",
      coffee_roaster: "Arm Blaster",
      small_market: "Small Posing Booth",
      hacienda: "Free Trial",
      construction_hut: "Rack Dealer",
      small_warehouse: "Small Locker",
      hospice: "Recovery Room",
      office: "Bro Science Desk",
      large_market: "Large Posing Booth",
      large_warehouse: "Large Locker",
      factory: "Superset Zone",
      university: "Form Check Class",
      harbor: "Mirror Wall",
      wharf: "Private Flex",
      guild_hall: "Bouldering",
      residence: "Tennis",
      fortress: "Great Saunter",
      customs_house: "Beer Mile",
      city_hall: "Hole Digging",
    },
    buildingDescriptions: buildingCopy({
      indigo: "back",
      sugar: "chest",
      tobacco: "shoulders",
      coffee: "arms",
      indigoSource: "back workouts",
      sugarSource: "chest workouts",
      tobaccoSource: "shoulder workouts",
      coffeeSource: "arm workouts",
      money: "protein",
      settler: "bulk",
      quarry: "squat rack",
      goods: "muscle group",
      captain: "flex",
      staff: "a gym bro",
      market: "posing booth",
      building: "station",
      harbor: "flex",
      wharf: "private flex",
      smallProduction: "small muscle station",
      largeProduction: "large",
      island: "workout",
      shipped: "flexed",
      civic: "gym",
    }),
    labels: {
      board: "Training Plan",
      plantations: "Workouts",
      quarries: "Squat racks",
      cargoShips: "Flex queues",
      tradingHouse: "Posing booth",
      colonistShip: "Gym bro van",
      goodsSupply: "Muscle groups",
      empty: "Open",
      open: "Open",
      goods: "Muscles",
      noGoods: "No muscles",
      island: "Routine",
      city: "Gym",
      sanJuan: "Bench",
      governor: "Alpha",
      doubloons: "protein",
      roles: "Splits",
      buildings: "Stations",
      quarry: "squat rack",
      quarriesPlural: "squat racks",
      finalScoring: "Final flex",
      shipped: "flexed",
      buildingScore: "stations",
    },
    actions: {
      chooseRole: "Choose a split.",
      choosingRole: (playerName) => `${playerName} is choosing a split.`,
      haciendaTile: "Free trial workout",
      mayorHelp: "Click bro dots on your routine and gym to spot lifts.",
      buildPrompt: "Install from the station market below or pass.",
      storagePrompt: "Discard until remaining muscles fit your locker.",
      take: "Take",
      sell: "Sell",
      ship: "Flex",
      onShip: "in queue",
      wharf: "Solo Flex",
      discard: "Cut",
    },
    messages: {
      changedTheme: (themeName) => `changed the split to ${themeName}`,
      choseRole: (playerName, roleName) => `${playerName} chose ${roleName}`,
      prospected: (playerName) => `${playerName} found a locker coin`,
      usedHacienda: (playerName, goodName) => `${playerName} used a free trial for ${goodName}`,
      settled: (playerName, plantationName) => `${playerName} added ${plantationName}`,
      settledQuarry: (playerName) => `${playerName} claimed a squat rack`,
      passed: (playerName) => `${playerName} skipped leg day`,
      recalledColonists: (playerName) => `${playerName} recalled gym bros`,
      placedColonist: (playerName) => `${playerName} spotted a lift`,
      movedColonistToSanJuan: (playerName) => `${playerName} moved a bro to bench`,
      finishedColonists: (playerName) => `${playerName} finished spotting`,
      built: (playerName, buildingName) => `${playerName} installed ${buildingName}`,
      tookExtraGood: (playerName, goodName) => `${playerName} took extra ${goodName}`,
      skippedExtraGood: (playerName) => `${playerName} skipped the extra pump`,
      producedGoods: () => "trained muscle groups",
      sold: (playerName, goodName) => `${playerName} sold ${goodName}`,
      shipped: (playerName, amount, goodName) => `${playerName} flexed ${amount} ${goodName}`,
      usedWharf: (playerName, amount, goodName) => `${playerName} solo-flexed ${amount} ${goodName}`,
      discarded: (playerName, goodName) => `${playerName} cut ${goodName}`,
      stored: (playerName) => `${playerName} packed the locker`,
      phaseFinished: (phaseName) => `${phaseName} finished`,
    },
  }),
  puerto_rifto: themed({
    gameName: "Puerto Rifto",
    phase: {
      role: "Draft pick",
      settler: "Laning",
      mayor: "Roam",
      builder: "Item shop",
      craftsman_bonus: "Farm bonus",
      trader: "Trade",
      captain: "Teamfight",
      storage: "Recall",
      game_over: "Nexus down",
    },
    roles: {
      settler: "Top Laner",
      mayor: "Support",
      builder: "Shopkeeper",
      craftsman: "Jungler",
      trader: "Mid Laner",
      captain: "Shotcaller",
      prospector_1: "Scuttle Crab",
      prospector_2: "Scuttle Crab",
    },
    roleDescriptions: {
      settler: "Everyone chooses a lane tile.",
      mayor: "Everyone places champions.",
      builder: "Everyone may buy one item.",
      craftsman: "Everyone drafts roles.",
      trader: "Everyone may trade one role.",
      captain: "Everyone teamfights for VP.",
      prospector_1: "No shared gank.",
      prospector_2: "No shared gank.",
    },
    roleRewards: {
      settler: "Chooser may take blue buff.",
      mayor: "Chooser takes 1 champion first.",
      builder: "Chooser pays 1 less.",
      craftsman: "Chooser may take 1 extra role.",
      trader: "Chooser earns +1 gold.",
      captain: "Chooser earns +1 VP once.",
      prospector_1: "Chooser takes 1 gold.",
      prospector_2: "Chooser takes 1 gold.",
    },
    goods: { corn: "Support", indigo: "ADC", sugar: "Jungle", tobacco: "Top", coffee: "Mid" },
    plantations: {
      corn: "Support",
      indigo: "ADC",
      sugar: "Jungle",
      tobacco: "Top",
      coffee: "Mid",
      quarry: "Blue Buff",
    },
    buildings: {
      small_indigo_plant: "Small ADC Queue",
      small_sugar_mill: "Small Jungle Camp",
      indigo_plant: "ADC Queue",
      sugar_mill: "Jungle Camp",
      tobacco_storage: "Top Island",
      coffee_roaster: "Mid Tower",
      small_market: "Small Shop",
      hacienda: "Side Quest",
      construction_hut: "Buff Path",
      small_warehouse: "Small Recall",
      hospice: "Fountain",
      office: "Brush Cheese",
      large_market: "Large Shop",
      large_warehouse: "Large Recall",
      factory: "Jungle Route",
      university: "Academy",
      harbor: "River Fight",
      wharf: "Teleport Play",
      guild_hall: "Andrew Cuomo",
      residence: "18th and Mission",
      fortress: "Silver Alpaca",
      customs_house: "Red Scharlach",
      city_hall: "Silver Finger",
    },
    buildingDescriptions: buildingCopy({
      indigo: "ADC",
      sugar: "jungle",
      tobacco: "top",
      coffee: "mid",
      indigoSource: "ADC lanes",
      sugarSource: "jungle lanes",
      tobaccoSource: "top lanes",
      coffeeSource: "mid lanes",
      money: "gold",
      settler: "laning",
      quarry: "blue buff",
      goods: "role",
      captain: "teamfight",
      staff: "a champion",
      market: "trade",
      building: "item",
      harbor: "river fight",
      wharf: "teleport",
      smallProduction: "small role item",
      largeProduction: "large",
      island: "lane",
      shipped: "scored",
      civic: "Rift",
    }),
    labels: {
      board: "Rift Map",
      plantations: "Lanes",
      quarries: "Blue buffs",
      cargoShips: "Teamfight lanes",
      tradingHouse: "Trade window",
      colonistShip: "Champion pool",
      goodsSupply: "Role supply",
      empty: "Open",
      open: "Open",
      goods: "Roles",
      noGoods: "No roles",
      island: "Lane",
      city: "Build",
      sanJuan: "Fountain",
      governor: "Shotcaller",
      doubloons: "gold",
      roles: "Draft",
      buildings: "Items",
      quarry: "blue buff",
      quarriesPlural: "blue buffs",
      finalScoring: "Nexus down",
      shipped: "scored",
      buildingScore: "items",
    },
    actions: {
      chooseRole: "Choose a pick.",
      choosingRole: (playerName) => `${playerName} is drafting a pick.`,
      haciendaTile: "Side quest lane",
      mayorHelp: "Click champion dots on your lane and build to set the comp.",
      buildPrompt: "Buy from the item shop below or pass.",
      storagePrompt: "Discard until remaining roles fit your recall.",
      take: "Take",
      sell: "Trade",
      ship: "Fight",
      onShip: "in lane",
      wharf: "Teleport",
      discard: "Drop",
    },
    messages: {
      changedTheme: (themeName) => `changed queue to ${themeName}`,
      choseRole: (playerName, roleName) => `${playerName} locked ${roleName}`,
      prospected: (playerName) => `${playerName} took scuttle`,
      usedHacienda: (playerName, goodName) => `${playerName} side-quested ${goodName}`,
      settled: (playerName, plantationName) => `${playerName} claimed ${plantationName}`,
      settledQuarry: (playerName) => `${playerName} took blue buff`,
      passed: (playerName) => `${playerName} backed off`,
      recalledColonists: (playerName) => `${playerName} recalled champions`,
      placedColonist: (playerName) => `${playerName} placed a champion`,
      movedColonistToSanJuan: (playerName) => `${playerName} recalled a champion`,
      finishedColonists: (playerName) => `${playerName} set the comp`,
      built: (playerName, buildingName) => `${playerName} bought ${buildingName}`,
      tookExtraGood: (playerName, goodName) => `${playerName} took extra ${goodName}`,
      skippedExtraGood: (playerName) => `${playerName} skipped the extra camp`,
      producedGoods: () => "drafted roles",
      sold: (playerName, goodName) => `${playerName} traded ${goodName}`,
      shipped: (playerName, amount, goodName) => `${playerName} fought for ${amount} ${goodName}`,
      usedWharf: (playerName, amount, goodName) => `${playerName} teleported for ${amount} ${goodName}`,
      discarded: (playerName, goodName) => `${playerName} dropped ${goodName}`,
      stored: (playerName) => `${playerName} recalled roles`,
      phaseFinished: (phaseName) => `${phaseName} finished`,
    },
  }),
  puerto_sicko: themed({
    gameName: "Puerto Sicko",
    phase: {
      role: "Shift choice",
      settler: "Admissions",
      mayor: "Rounds",
      builder: "Facilities",
      craftsman_bonus: "Lab bonus",
      trader: "Billing",
      captain: "Discharge",
      storage: "Supply closet",
      game_over: "Final chart",
    },
    roles: {
      settler: "Intake Nurse",
      mayor: "Charge Nurse",
      builder: "Facilities",
      craftsman: "Lab Tech",
      trader: "Billing Clerk",
      captain: "Discharge Planner",
      prospector_1: "Insurance Rep",
      prospector_2: "Insurance Rep",
    },
    roleDescriptions: {
      settler: "Everyone chooses a ward tile.",
      mayor: "Everyone places staff.",
      builder: "Everyone may open one room.",
      craftsman: "Everyone processes charts.",
      trader: "Everyone may bill one chart.",
      captain: "Everyone discharges charts for VP.",
      prospector_1: "No shared procedure.",
      prospector_2: "No shared procedure.",
    },
    roleRewards: {
      settler: "Chooser may take an MRI.",
      mayor: "Chooser takes 1 staff first.",
      builder: "Chooser pays 1 less.",
      craftsman: "Chooser may take 1 extra chart.",
      trader: "Chooser earns +1 copay.",
      captain: "Chooser earns +1 VP once.",
      prospector_1: "Chooser takes 1 copay.",
      prospector_2: "Chooser takes 1 copay.",
    },
    goods: { corn: "Eyes", indigo: "Heart", sugar: "Lungs", tobacco: "Neuro", coffee: "Chakra" },
    plantations: {
      corn: "Eyes",
      indigo: "Heart",
      sugar: "Lungs",
      tobacco: "Neuro",
      coffee: "Chakra",
      quarry: "MRI",
    },
    buildings: {
      small_indigo_plant: "Small Heart Cart",
      small_sugar_mill: "Small Lung Room",
      indigo_plant: "Heart Cart",
      sugar_mill: "Lung Room",
      tobacco_storage: "Neuro Lab",
      coffee_roaster: "Chakra Desk",
      small_market: "Small Billing Desk",
      hacienda: "Walk-in Clinic",
      construction_hut: "MRI Referral",
      small_warehouse: "Small Supply Closet",
      hospice: "Triage Bay",
      office: "Chart Review",
      large_market: "Large Billing Desk",
      large_warehouse: "Large Supply Closet",
      factory: "Lab Wing",
      university: "Teaching Hospital",
      harbor: "Discharge Desk",
      wharf: "Ambulance Bay",
      guild_hall: "Fauci",
      residence: "Oz",
      fortress: "RFK Jr",
      customs_house: "Chopra",
      city_hall: "Bryan Johnson",
    },
    buildingDescriptions: buildingCopy({
      indigo: "heart",
      sugar: "lungs",
      tobacco: "neuro",
      coffee: "chakra",
      indigoSource: "heart wards",
      sugarSource: "lung wards",
      tobaccoSource: "neuro wards",
      coffeeSource: "chakra wards",
      money: "copays",
      settler: "admissions",
      quarry: "MRI",
      goods: "chart",
      captain: "discharge",
      staff: "staff",
      market: "billing",
      building: "room",
      harbor: "discharge",
      wharf: "ambulance",
      smallProduction: "small treatment room",
      largeProduction: "large",
      island: "ward",
      shipped: "discharged",
      civic: "hospital",
    }),
    labels: {
      board: "Hospital Board",
      plantations: "Wards",
      quarries: "MRIs",
      cargoShips: "Discharge lanes",
      tradingHouse: "Billing window",
      colonistShip: "Staff pool",
      goodsSupply: "Chart supply",
      empty: "Open",
      open: "Open",
      goods: "Charts",
      noGoods: "No charts",
      island: "Ward",
      city: "Hospital",
      sanJuan: "Break room",
      governor: "Chief",
      doubloons: "copays",
      roles: "Shifts",
      buildings: "Rooms",
      quarry: "MRI",
      quarriesPlural: "MRIs",
      finalScoring: "Final chart",
      shipped: "discharged",
      buildingScore: "rooms",
    },
    actions: {
      chooseRole: "Choose a shift.",
      choosingRole: (playerName) => `${playerName} is choosing a shift.`,
      haciendaTile: "Walk-in ward",
      mayorHelp: "Click staff dots on your ward and hospital to cover rounds.",
      buildPrompt: "Open from the room market below or pass.",
      storagePrompt: "Discard until remaining charts fit your supply closet.",
      take: "Take",
      sell: "Bill",
      ship: "Discharge",
      onShip: "in lane",
      wharf: "Ambulance",
      discard: "Chart",
    },
    messages: {
      changedTheme: (themeName) => `changed the ward to ${themeName}`,
      choseRole: (playerName, roleName) => `${playerName} took ${roleName}`,
      prospected: (playerName) => `${playerName} found insurance money`,
      usedHacienda: (playerName, goodName) => `${playerName} admitted walk-in ${goodName}`,
      settled: (playerName, plantationName) => `${playerName} opened ${plantationName}`,
      settledQuarry: (playerName) => `${playerName} booked an MRI`,
      passed: (playerName) => `${playerName} paged out`,
      recalledColonists: (playerName) => `${playerName} recalled staff`,
      placedColonist: (playerName) => `${playerName} covered a room`,
      movedColonistToSanJuan: (playerName) => `${playerName} sent staff to break room`,
      finishedColonists: (playerName) => `${playerName} finished rounds`,
      built: (playerName, buildingName) => `${playerName} opened ${buildingName}`,
      tookExtraGood: (playerName, goodName) => `${playerName} took extra ${goodName}`,
      skippedExtraGood: (playerName) => `${playerName} skipped the extra chart`,
      producedGoods: () => "processed charts",
      sold: (playerName, goodName) => `${playerName} billed ${goodName}`,
      shipped: (playerName, amount, goodName) => `${playerName} discharged ${amount} ${goodName}`,
      usedWharf: (playerName, amount, goodName) => `${playerName} ambulanced ${amount} ${goodName}`,
      discarded: (playerName, goodName) => `${playerName} charted ${goodName}`,
      stored: (playerName) => `${playerName} stocked the supply closet`,
      phaseFinished: (phaseName) => `${phaseName} finished`,
    },
  }),
  puerto_yugioh: themed({
    gameName: "Puerto Yugioh",
    phase: {
      role: "Turn choice",
      settler: "Field phase",
      mayor: "Summon phase",
      builder: "Deck build",
      craftsman_bonus: "Draw bonus",
      trader: "Trade phase",
      captain: "Battle phase",
      storage: "Hand limit",
      game_over: "Final duel",
    },
    roles: {
      settler: "Field Spell",
      mayor: "Summoner",
      builder: "Deck Builder",
      craftsman: "Card Printer",
      trader: "Card Trader",
      captain: "Duel Captain",
      prospector_1: "Greedy Pot",
      prospector_2: "Greedy Pot",
    },
    roleDescriptions: {
      settler: "Everyone chooses a zone tile.",
      mayor: "Everyone places duelists.",
      builder: "Everyone may sleeve one card.",
      craftsman: "Everyone draws combo pieces.",
      trader: "Everyone may trade one summon.",
      captain: "Everyone battles summons for VP.",
      prospector_1: "No shared effect.",
      prospector_2: "No shared effect.",
    },
    roleRewards: {
      settler: "Chooser may take an item.",
      mayor: "Chooser takes 1 duelist first.",
      builder: "Chooser pays 1 less.",
      craftsman: "Chooser may draw 1 extra summon.",
      trader: "Chooser earns +1 star.",
      captain: "Chooser earns +1 VP once.",
      prospector_1: "Chooser takes 1 star.",
      prospector_2: "Chooser takes 1 star.",
    },
    goods: { corn: "Fusion", indigo: "Synchro", sugar: "Xyz", tobacco: "Ritual", coffee: "Pendulum" },
    plantations: {
      corn: "Fusion",
      indigo: "Synchro",
      sugar: "Xyz",
      tobacco: "Ritual",
      coffee: "Pendulum",
      quarry: "Item",
    },
    buildings: {
      small_indigo_plant: "Small Synchro Mill",
      small_sugar_mill: "Small Xyz Forge",
      indigo_plant: "Synchro Mill",
      sugar_mill: "Xyz Forge",
      tobacco_storage: "Ritual Altar",
      coffee_roaster: "Pendulum Roost",
      small_market: "Small Card Shop",
      hacienda: "Mystery Booster",
      construction_hut: "Item Finder",
      small_warehouse: "Small Binder",
      hospice: "Summon Clinic",
      office: "Rule Lawyer",
      large_market: "Large Card Shop",
      large_warehouse: "Large Binder",
      factory: "Combo Engine",
      university: "Duel Academy",
      harbor: "Battle Dock",
      wharf: "Direct Attack",
      guild_hall: "Joey",
      residence: "Yugi",
      fortress: "Pegasus",
      customs_house: "Kaiba",
      city_hall: "Bandit Keith",
    },
    buildingDescriptions: buildingCopy({
      indigo: "synchro",
      sugar: "Xyz",
      tobacco: "ritual",
      coffee: "pendulum",
      indigoSource: "synchro zones",
      sugarSource: "Xyz zones",
      tobaccoSource: "ritual zones",
      coffeeSource: "pendulum zones",
      money: "stars",
      settler: "field",
      quarry: "item",
      goods: "summon",
      captain: "battle",
      staff: "duelist",
      market: "trade",
      building: "card",
      harbor: "battle",
      wharf: "direct attack",
      smallProduction: "small summon card",
      largeProduction: "large",
      island: "zone",
      shipped: "battled",
      civic: "duel",
    }),
    labels: {
      board: "Duel Board",
      plantations: "Zones",
      quarries: "Items",
      cargoShips: "Battle lanes",
      tradingHouse: "Trade binder",
      colonistShip: "Duelist pool",
      goodsSupply: "Summon supply",
      empty: "Open",
      open: "Open",
      goods: "Summons",
      noGoods: "No summons",
      island: "Zone",
      city: "Deck",
      sanJuan: "Graveyard",
      governor: "King",
      doubloons: "stars",
      roles: "Turns",
      buildings: "Cards",
      quarry: "item",
      quarriesPlural: "items",
      finalScoring: "Final duel",
      shipped: "battled",
      buildingScore: "cards",
    },
    actions: {
      chooseRole: "Choose a turn.",
      choosingRole: (playerName) => `${playerName} is choosing a turn.`,
      haciendaTile: "Mystery zone",
      mayorHelp: "Click duelist dots on your zones and deck to set the board.",
      buildPrompt: "Sleeve from the card shop below or pass.",
      storagePrompt: "Discard until remaining summons fit your binder.",
      take: "Take",
      sell: "Trade",
      ship: "Battle",
      onShip: "in lane",
      wharf: "Direct",
      discard: "Discard",
    },
    messages: {
      changedTheme: (themeName) => `changed duel disk to ${themeName}`,
      choseRole: (playerName, roleName) => `${playerName} activated ${roleName}`,
      prospected: (playerName) => `${playerName} drew stars`,
      usedHacienda: (playerName, goodName) => `${playerName} cracked a booster for ${goodName}`,
      settled: (playerName, plantationName) => `${playerName} set ${plantationName}`,
      settledQuarry: (playerName) => `${playerName} equipped an item`,
      passed: (playerName) => `${playerName} ended turn`,
      recalledColonists: (playerName) => `${playerName} recalled duelists`,
      placedColonist: (playerName) => `${playerName} summoned a duelist`,
      movedColonistToSanJuan: (playerName) => `${playerName} sent a duelist to the graveyard`,
      finishedColonists: (playerName) => `${playerName} finished summoning`,
      built: (playerName, buildingName) => `${playerName} sleeved ${buildingName}`,
      tookExtraGood: (playerName, goodName) => `${playerName} drew extra ${goodName}`,
      skippedExtraGood: (playerName) => `${playerName} skipped the extra draw`,
      producedGoods: () => "drew combo pieces",
      sold: (playerName, goodName) => `${playerName} traded ${goodName}`,
      shipped: (playerName, amount, goodName) => `${playerName} battled with ${amount} ${goodName}`,
      usedWharf: (playerName, amount, goodName) => `${playerName} attacked directly with ${amount} ${goodName}`,
      discarded: (playerName, goodName) => `${playerName} discarded ${goodName}`,
      stored: (playerName) => `${playerName} packed the binder`,
      phaseFinished: (phaseName) => `${phaseName} finished`,
    },
  }),
  puerto_rato: themed({
    gameName: "Puerto Rato",
    phase: {
      role: "Scheme choice",
      settler: "Scouting",
      mayor: "Muster",
      builder: "Burrow build",
      craftsman_bonus: "Hoard bonus",
      trader: "Fence goods",
      captain: "Raid lanes",
      storage: "Nest stash",
      game_over: "Empire tally",
    },
    roles: {
      settler: "Tunnel Scout",
      mayor: "Brood Marshal",
      builder: "Burrow Boss",
      craftsman: "Scrap Sorter",
      trader: "Back Alley Fence",
      captain: "Raid Captain",
      prospector_1: "Coin Sniffer",
      prospector_2: "Coin Sniffer",
    },
    roleDescriptions: {
      settler: "Everyone claims a borough tile.",
      mayor: "Everyone places rats.",
      builder: "Everyone may dig one room.",
      craftsman: "Everyone gathers hoard goods.",
      trader: "Everyone may fence one good.",
      captain: "Everyone raids goods for VP.",
      prospector_1: "No shared scheme.",
      prospector_2: "No shared scheme.",
    },
    roleRewards: {
      settler: "Chooser may take a tunnel.",
      mayor: "Chooser takes 1 rat first.",
      builder: "Chooser pays 1 less.",
      craftsman: "Chooser may take 1 extra good.",
      trader: "Chooser earns +1 coin.",
      captain: "Chooser earns +1 VP once.",
      prospector_1: "Chooser takes 1 coin.",
      prospector_2: "Chooser takes 1 coin.",
    },
    goods: { corn: "Trash", indigo: "Lint", sugar: "Cheese", tobacco: "Crumbs", coffee: "Pizza" },
    plantations: {
      corn: "Trash",
      indigo: "Lint",
      sugar: "Cheese",
      tobacco: "Crumbs",
      coffee: "Pizza",
      quarry: "Tunnel",
    },
    buildings: {
      small_indigo_plant: "Small Lint Nest",
      small_sugar_mill: "Small Cheese Den",
      indigo_plant: "Lint Nest",
      sugar_mill: "Cheese Den",
      tobacco_storage: "Crumb Cache",
      coffee_roaster: "Pizza Oven",
      small_market: "Small Trash Market",
      hacienda: "Loose Floorboard",
      construction_hut: "Tunnel Permit",
      small_warehouse: "Small Stash Hole",
      hospice: "Nursery Nook",
      office: "Permit Office",
      large_market: "Large Trash Market",
      large_warehouse: "Large Stash Hole",
      factory: "Junkworks",
      university: "Rat Academy",
      harbor: "Storm Drain",
      wharf: "Secret Pipe",
      guild_hall: "Zohran Mamdani",
      residence: "Curtis Sliwa",
      fortress: "Andrew Cuomo",
      customs_house: "Eric Adams",
      city_hall: "Rudy Giuliani",
    },
    buildingDescriptions: buildingCopy({
      indigo: "lint",
      sugar: "cheese",
      tobacco: "crumbs",
      coffee: "pizza",
      indigoSource: "lint boroughs",
      sugarSource: "cheese boroughs",
      tobaccoSource: "crumb boroughs",
      coffeeSource: "pizza boroughs",
      money: "coins",
      settler: "scouting",
      quarry: "tunnel",
      goods: "good",
      captain: "raid",
      staff: "rat",
      market: "fence",
      building: "room",
      harbor: "raid",
      wharf: "secret pipe",
      smallProduction: "small hoard room",
      largeProduction: "large",
      island: "borough",
      shipped: "raided",
      civic: "empire",
    }),
    labels: {
      board: "Empire Board",
      plantations: "Boroughs",
      quarries: "Tunnels",
      cargoShips: "Raid lanes",
      tradingHouse: "Fence window",
      colonistShip: "Rat wagon",
      goodsSupply: "Street supply",
      empty: "Open",
      open: "Open",
      goods: "Hoard",
      noGoods: "No hoard",
      island: "Borough",
      city: "Burrow",
      sanJuan: "Drainpipe",
      governor: "Rat King",
      doubloons: "coins",
      roles: "Schemes",
      buildings: "Rooms",
      quarry: "tunnel",
      quarriesPlural: "tunnels",
      finalScoring: "Empire tally",
      shipped: "raided",
      buildingScore: "rooms",
    },
    actions: {
      chooseRole: "Choose a scheme.",
      choosingRole: (playerName) => `${playerName} is choosing a scheme.`,
      haciendaTile: "Loose tile",
      mayorHelp: "Click rat dots on your boroughs and burrow to staff the empire.",
      buildPrompt: "Dig from the room market below or pass.",
      storagePrompt: "Discard until remaining hoard fits your stash holes.",
      take: "Take",
      sell: "Fence",
      ship: "Raid",
      onShip: "in lane",
      wharf: "Pipe",
      discard: "Drop",
    },
    messages: {
      changedTheme: (themeName) => `changed empire banner to ${themeName}`,
      choseRole: (playerName, roleName) => `${playerName} chose ${roleName}`,
      prospected: (playerName) => `${playerName} sniffed out coins`,
      usedHacienda: (playerName, goodName) => `${playerName} found loose ${goodName}`,
      settled: (playerName, plantationName) => `${playerName} claimed ${plantationName}`,
      settledQuarry: (playerName) => `${playerName} dug a tunnel`,
      passed: (playerName) => `${playerName} scurried past`,
      recalledColonists: (playerName) => `${playerName} recalled rats`,
      placedColonist: (playerName) => `${playerName} posted a rat`,
      movedColonistToSanJuan: (playerName) => `${playerName} sent a rat to the drainpipe`,
      finishedColonists: (playerName) => `${playerName} finished muster`,
      built: (playerName, buildingName) => `${playerName} dug ${buildingName}`,
      tookExtraGood: (playerName, goodName) => `${playerName} grabbed extra ${goodName}`,
      skippedExtraGood: (playerName) => `${playerName} skipped the extra scrap`,
      producedGoods: () => "sorted the hoard",
      sold: (playerName, goodName) => `${playerName} fenced ${goodName}`,
      shipped: (playerName, amount, goodName) => `${playerName} raided ${amount} ${goodName}`,
      usedWharf: (playerName, amount, goodName) => `${playerName} piped away ${amount} ${goodName}`,
      discarded: (playerName, goodName) => `${playerName} dropped ${goodName}`,
      stored: (playerName) => `${playerName} packed the stash`,
      phaseFinished: (phaseName) => `${phaseName} finished`,
    },
  }),
  los_santos_rico: themed({
    gameName: "Los Santos Rico",
    phase: {
      role: "Job choice",
      settler: "Turf scout",
      mayor: "Crew call",
      builder: "Property buy",
      craftsman_bonus: "Hustle bonus",
      trader: "Fence meet",
      captain: "Export run",
      storage: "Safehouse stash",
      game_over: "Final score",
    },
    roles: {
      settler: "Turf Scout",
      mayor: "Crew Boss",
      builder: "Property Broker",
      craftsman: "Hustler",
      trader: "Street Fence",
      captain: "Getaway Driver",
      prospector_1: "Side Hustle",
      prospector_2: "Side Hustle",
    },
    roleDescriptions: {
      settler: "Everyone claims a block tile.",
      mayor: "Everyone places crew.",
      builder: "Everyone may buy one property.",
      craftsman: "Everyone works their hustle.",
      trader: "Everyone may fence one score.",
      captain: "Everyone exports scores for VP.",
      prospector_1: "No shared job.",
      prospector_2: "No shared job.",
    },
    roleRewards: {
      settler: "Chooser may take a garage.",
      mayor: "Chooser takes 1 crew first.",
      builder: "Chooser pays 1 less.",
      craftsman: "Chooser may take 1 extra score.",
      trader: "Chooser earns +1 cash.",
      captain: "Chooser earns +1 VP once.",
      prospector_1: "Chooser takes 1 cash.",
      prospector_2: "Chooser takes 1 cash.",
    },
    goods: { corn: "Snacks", indigo: "Paint", sugar: "Cash", tobacco: "Contraband", coffee: "Supercars" },
    plantations: {
      corn: "Snacks",
      indigo: "Paint",
      sugar: "Cash",
      tobacco: "Contraband",
      coffee: "Supercars",
      quarry: "Garage",
    },
    buildings: {
      small_indigo_plant: "Small Paint Shop",
      small_sugar_mill: "Small Cash Room",
      indigo_plant: "Paint Shop",
      sugar_mill: "Cash Room",
      tobacco_storage: "Contraband Lockup",
      coffee_roaster: "Supercar Garage",
      small_market: "Small Street Market",
      hacienda: "Backroad Tip",
      construction_hut: "Garage Permit",
      small_warehouse: "Small Safehouse",
      hospice: "Crew Clinic",
      office: "Paperwork Guy",
      large_market: "Large Street Market",
      large_warehouse: "Large Safehouse",
      factory: "Chop Shop",
      university: "Driving School",
      harbor: "Export Dock",
      wharf: "Solo Run",
      guild_hall: "Crew HQ",
      residence: "Vinewood Villa",
      fortress: "Wanted Bunker",
      customs_house: "Import Office",
      city_hall: "City Contract",
    },
    buildingDescriptions: buildingCopy({
      indigo: "paint",
      sugar: "cash",
      tobacco: "contraband",
      coffee: "supercars",
      indigoSource: "paint blocks",
      sugarSource: "cash blocks",
      tobaccoSource: "contraband blocks",
      coffeeSource: "supercar blocks",
      money: "cash",
      settler: "turf",
      quarry: "garage",
      goods: "score",
      captain: "export",
      staff: "crew",
      market: "fence",
      building: "property",
      harbor: "export",
      wharf: "solo run",
      smallProduction: "small hustle property",
      largeProduction: "large",
      island: "block",
      shipped: "exported",
      civic: "city",
    }),
    labels: {
      board: "Los Santos Board",
      plantations: "Blocks",
      quarries: "Garages",
      cargoShips: "Export lanes",
      tradingHouse: "Fence meet",
      colonistShip: "Crew van",
      goodsSupply: "Street supply",
      empty: "Open",
      open: "Open",
      goods: "Scores",
      noGoods: "No scores",
      island: "Block",
      city: "Safehouse",
      sanJuan: "County lockup",
      governor: "Boss",
      doubloons: "cash",
      roles: "Jobs",
      buildings: "Properties",
      quarry: "garage",
      quarriesPlural: "garages",
      finalScoring: "Final score",
      shipped: "exported",
      buildingScore: "properties",
    },
    actions: {
      chooseRole: "Choose a job.",
      choosingRole: (playerName) => `${playerName} is choosing a job.`,
      haciendaTile: "Backroad block",
      mayorHelp: "Click crew dots on your blocks and safehouse to staff the job.",
      buildPrompt: "Buy from the property market below or pass.",
      storagePrompt: "Discard until remaining scores fit your safehouse stash.",
      take: "Take",
      sell: "Fence",
      ship: "Export",
      onShip: "in lane",
      wharf: "Solo",
      discard: "Dump",
    },
    messages: {
      changedTheme: (themeName) => `changed the radio station to ${themeName}`,
      choseRole: (playerName, roleName) => `${playerName} took ${roleName}`,
      prospected: (playerName) => `${playerName} ran a side hustle`,
      usedHacienda: (playerName, goodName) => `${playerName} found backroad ${goodName}`,
      settled: (playerName, plantationName) => `${playerName} claimed ${plantationName}`,
      settledQuarry: (playerName) => `${playerName} opened a garage`,
      passed: (playerName) => `${playerName} laid low`,
      recalledColonists: (playerName) => `${playerName} recalled the crew`,
      placedColonist: (playerName) => `${playerName} posted crew`,
      movedColonistToSanJuan: (playerName) => `${playerName} sent crew to county lockup`,
      finishedColonists: (playerName) => `${playerName} finished the crew call`,
      built: (playerName, buildingName) => `${playerName} bought ${buildingName}`,
      tookExtraGood: (playerName, goodName) => `${playerName} grabbed extra ${goodName}`,
      skippedExtraGood: (playerName) => `${playerName} skipped the extra score`,
      producedGoods: () => "worked the hustles",
      sold: (playerName, goodName) => `${playerName} fenced ${goodName}`,
      shipped: (playerName, amount, goodName) => `${playerName} exported ${amount} ${goodName}`,
      usedWharf: (playerName, amount, goodName) => `${playerName} ran solo with ${amount} ${goodName}`,
      discarded: (playerName, goodName) => `${playerName} dumped ${goodName}`,
      stored: (playerName) => `${playerName} packed the safehouse`,
      phaseFinished: (phaseName) => `${phaseName} finished`,
    },
  }),
};

export function isPuertoRicoThemeKey(value: string | undefined): value is PuertoRicoThemeKey {
  return THEME_KEYS.includes(value as PuertoRicoThemeKey);
}

export function getThemeKey(): PuertoRicoThemeKey {
  const key = store.gameW?.game?.themeKey;
  return isPuertoRicoThemeKey(key) ? key : DEFAULT_THEME_KEY;
}

export function getTheme(): ThemeText {
  return THEMES[getThemeKey()];
}

export const theme = new Proxy(puertoRico, {
  get(_target, property: keyof ThemeText) {
    return getTheme()[property];
  },
}) as ThemeText;

export const goodsInThemeOrder = GOOD_IDS;
