import { BuildingId, GOOD_IDS, GoodId, PlantationId, RoleId } from "../utils/rules";

export const theme = {
  gameName: "Puerto Rico",
  rulesUrl: "https://www.riograndegames.com/wp-content/uploads/2013/02/Puerto-Rico-Rules.pdf",
  phase: {
    role: "Role choice",
    settler: "Settler",
    mayor: "Mayor",
    builder: "Builder",
    craftsman_bonus: "Craftsman bonus",
    trader: "Trader",
    captain: "Captain",
    storage: "Storage",
    game_over: "Game over",
  },
  roles: {
    settler: "Settler",
    mayor: "Mayor",
    builder: "Builder",
    craftsman: "Craftsman",
    trader: "Trader",
    captain: "Captain",
    prospector_1: "Prospector",
    prospector_2: "Prospector",
  } as Record<RoleId, string>,
  goods: {
    corn: "Corn",
    indigo: "Indigo",
    sugar: "Sugar",
    tobacco: "Tobacco",
    coffee: "Coffee",
  } as Record<GoodId, string>,
  plantations: {
    corn: "Corn",
    indigo: "Indigo",
    sugar: "Sugar",
    tobacco: "Tobacco",
    coffee: "Coffee",
    quarry: "Quarry",
  } as Record<PlantationId, string>,
  colors: {
    corn: "#f3d66b",
    indigo: "#6e91c8",
    sugar: "#f7f4e6",
    tobacco: "#c18b5a",
    coffee: "#775042",
    quarry: "#b8babd",
    violet: "#d9c3ea",
    large: "#c9b48d",
  } as Record<GoodId | "quarry" | "violet" | "large", string>,
  buildings: {
    small_indigo_plant: "Small Indigo Plant",
    small_sugar_mill: "Small Sugar Mill",
    indigo_plant: "Indigo Plant",
    sugar_mill: "Sugar Mill",
    tobacco_storage: "Tobacco Storage",
    coffee_roaster: "Coffee Roaster",
    small_market: "Small Market",
    hacienda: "Hacienda",
    construction_hut: "Construction Hut",
    small_warehouse: "Small Warehouse",
    hospice: "Hospice",
    office: "Office",
    large_market: "Large Market",
    large_warehouse: "Large Warehouse",
    factory: "Factory",
    university: "University",
    harbor: "Harbor",
    wharf: "Wharf",
    guild_hall: "Guild Hall",
    residence: "Residence",
    fortress: "Fortress",
    customs_house: "Customs House",
    city_hall: "City Hall",
  } as Record<BuildingId, string>,
  disabledPower: "Power disabled in core v1",
  controls: {
    newGame: "New Game",
    pass: "Pass",
    finishPlacement: "Finish placement",
    clearColonists: "Clear colonists",
    skipBonus: "Skip bonus",
    finishStorage: "Finish storage",
  },
};

export const goodsInThemeOrder = GOOD_IDS;
